### ISSUE TITLE
[FEATURE] Support call alias in signing

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wash-archive#101]
**Is your feature request related to a problem? Please describe.**
No problem

**Describe the solution you'd like**
Add the ability to specify an actor's call alias while signing the actor

**Describe alternatives you've considered**
None

**Additional context**
The call alias field is now available in the `Claims<Actor>` struct from `wascap`, so adding this feature would be a matter of just supporting the setting of this field at signing time.

**Comment by brooksmtownsend** [comment]
All call aliases should comply with the following restrictions:
- Alphanumeric characters, underscores, and hyphens allowed. All other non-alphanumeric characters should be omitted
- No 56 character uppercase values, public keys should _never_ be used as a call alias

**Comment by autodidaddict** [comment]
I think we might also want to permit `/` , as something that is hyphen-like that might allow for developers to convey a kind of hierarchical notation on calls if they want. This might allow us to put all our sample actors in the `wasmcloud/samples/echo` format rather than `wasmcloud-samples-echo`, where the first feels like a natural way of describing them even though it's "just a string" and we're not actually doing anything hierarchical.

Letting people use `-` and `/` should make it easy to come up with naming conventions that prevent alias conflicts in large lattices.
