### ISSUE TITLE
[FEATURE] Add command to query actor ID, Provider ID and capability

### ISSUE THREAD

**Issue by snnsnn** [wasmCloud/wash-archive#117]
**Is your feature request related to a problem? Please describe.**

Having ability to get actor or capability properties via command can help with command chaining in terminal window and also helps with tooling e.g generating manifest file via make commands.

#116

**Comment by autodidaddict** [comment]
Would using claims inspect or par inspect with json output and then piping the results through jq give you what you need?

**Comment by LiamRandall** [comment]
@autodidaddict is that the experience we want people to have?

**Comment by autodidaddict** [comment]
Need to get more clarity here because I'm not entirely sure what @snnsnn is looking for.

**Comment by brooksmtownsend** [comment]
Inside of the REPL we'll certainly have challenges with handling JSON as we'd need to leverage something like [jq-rs](https://crates.io/crates/jq-rs), but the intent with the `--output json` flag is for people to be able to script it. All commands (other than `wash up`) support the output flag ATM

**Comment by snnsnn** [comment]
@autodidaddict @brooksmtownsend `jq` and `--output=json` covers my use case. I was after crating a manifest file via make command.

**Comment by brooksmtownsend** [comment]
@snnsnn for clarity, is this issue looking for a command that can essentially "export" the state of a REPL in a manifest file? e.g.

```
wash up
ctl start actor wasmcloud.azurecr.io/echo:0.2.0
export manifest # REPL only command to create a manifest from the embedded REPL host
```
Or are you looking for something different?

**Comment by snnsnn** [comment]
@brooksmtownsend  When I opened the issue, I had two things in mind: A way to chain commands in terminal session to avoid copying and pasting IDs whether in REPL or outside of it, and generating manifest.yml via make command which is basically the same thing. 

At the time I was not aware of `--output=json` option, at least not clearly, and it did not occurred to me to use `jq` and `--output=json` together. These two covers non REPL use case.

For the REPL use case, getting actor ID from the actor via dedicated commands and feeding it into another one may sound good but typing long list of names may not offer better user experience: 

```bash
ctl link $(get actor wasmcloud.azurecr.io/echo:0.2.0 --id) $(get provider wasmcloud.azurecr.io/httpserver:0.11.1 --id) $(get provider wasmcloud.azurecr.io/httpserver:0.11.1 --capability) PORT=8080
```
It may complicate things unnecessarily or may not be feasible at all. Typing first few letters of the ID's clearly offers superior alternative:

```bash
ctl link MCUD VAG3 YJ wasmcloud:httpserver PORT=8080
```

I think there was an issue to that effect but unfortunately I could not find it for linking.

Currently  `jq` and `--output=json` is good enough for me, if you want we can close this issue and wait for more use cases to emerge for something similar.

**Comment by brooksmtownsend** [comment]
I think we'll close this issue just because #74 partially covers this issue, we have intentions of shortening the public keys in the REPL (of course with an option of showing the full pub key) and adding some kind of autocomplete either via TAB completion or just allowing users to type in the first few letters of the public key
