### ISSUE TITLE
[FEATURE] Capture crash information

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wash-archive#136]
**Is your feature request related to a problem? Please describe.**
Related to #35, if there is a panic or a bad `unwrap` within the REPL the entire program can crash without indicating the source of the issue.

**Describe the solution you'd like**
If a crash occurs, either due to an unwrap or a panic somewhere in the execution of the REPL, information should be captured about the crash to at least point users to the offending error.

**Describe alternatives you've considered**
As mentioned in #35, an alternative is to try and catch every panic. This may be feasible for the REPL code, however we cannot guarantee that panics will not occur in crates we depend on.

**Comment by autodidaddict** [comment]
REPL is deprecated, closing.
