### ISSUE TITLE
[FEATURE] Use wasmcloud cache for inspect commands

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wash-archive#138]
**Is your feature request related to a problem? Please describe.**
Currently, both `wash claims inspect` and `wash par inspect` do not refer to the wasmcloud cache before downloading an actor or provider from an OCI registry. This causes the `inspect` command to take longer than it should, as OCI references are intended to be immutable.

**Describe the solution you'd like**
Following the same process as `wasmcloud-host` does, `wash claims inspect` and `wash par inspect` should read and write from/to the cache stored in the user's temp directory. This logic can be found in the [cached_file](https://github.com/wasmCloud/wasmCloud/blob/main/crates/wasmcloud-host/src/oci.rs#L68-L80) function.

**Comment by brooksmtownsend** [comment]
For an initial implementation, I imagine this essentially being a copy-paste from the linked `cached_file` function

**Comment by brooksmtownsend** [comment]
@stevelr I'm okay with moving this to the Post MVP scope as it has some implications around inspecting what's in a local registry, thoughts?

**Comment by brooksmtownsend** [comment]
Regarding my above comment, the _implication_ is as follows:

If an actor/provider is present in the local cache, then the idea is that  `wash claims inspect` would display the embedded claims in the cached file rather than fetching the latest artifact (if it changed). I actually think this is intended behavior, as it shows you the information about the actor/provider that the host will start.

What I'd love to see for this issue is to:
1. Inspect artifacts in the local cache. The Rust code to determine where an actor is stored can be found [here](https://github.com/wasmCloud/wasmcloud-otp/blob/main/host_core/native/hostcore_wasmcloud_native/src/oci.rs#L66-L78), and the provider code is [here](https://github.com/wasmCloud/wasmcloud-otp/blob/main/host_core/native/hostcore_wasmcloud_native/src/par.rs#L55_L81)
~2. Add a `--disable-cache` boolean flag that will fetch the latest artifact from the OCI URL and overwrite the local cache. This could be derived from an environment variable like `WASH_DISABLE_CACHE` in order to disable cache and always fetch the latest artifact.~
2. Add a `--no-cache` boolean flag that will fetch the latest artifact from the OCI URL and overwrite the local cache. This could be derived from an environment variable like `WASH_NO_CACHE` in order to disable cache and always fetch the latest artifact. (changed from `disable-cache` as per @stevelr 's good suggestion)

**Comment by stevelr** [comment]
nit: to me "disable" sounds like it might mean turning the cache off for longer than the duration of the current command. For example, "disable" for systemd services means turning them off for the next boot.  --no-cache sounds more temporary.
