### ISSUE TITLE
[FEATURE] Allow disabling strict capability update checks with embedded host

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wash-archive#141]
**Is your feature request related to a problem? Please describe.**
The `wash` REPL is primarily used for rapid development, and the embedded REPL host should enforce defaults that provide for quick iteration in a development environment. Currently, when updating an actor running on the embedded host, `wash` does not disable strict capability update checks, which prevents `--watch` from updating an actor if additional capabilities are added.

**Describe the solution you'd like**
For a seamless development experience, the embedded host should disable strict capability update checks (see [HostBuilder documentation method](https://docs.rs/wasmcloud-host/0.18.1/wasmcloud_host/struct.HostBuilder.html#method.disable_strict_update_check)) and allow a flag to be passed to `wash up` to enable strict update checking (e.g. by not calling that method). 

**Describe alternatives you've considered**
An alternative would be to keep the current behavior as-is, but allow users to pass a `--disable-strict-update-check` to the `wash up` command instead. I think this leads to higher friction than the solution above, as most REPL users will be looking for a seamless experience.

**Additional context**
Note: this only affects the _embedded_ REPL host. Any other host that the REPL can access via lattice sets this flag as the host is being built, so `wash` cannot change this flag on any other running host.

**Comment by autodidaddict** [comment]
If I understand this right, the solution is just to make the embedded host created by the REPL not enable the strict update check, right?

**Comment by brooksmtownsend** [comment]
@autodidaddict The embedded host has to explicitly disable the strict update check, since the default is to have it enabled. So, yes 👍🏻

**Comment by autodidaddict** [comment]
wash REPL is deprecated. Closing.
