### ISSUE TITLE
[FEATURE] REPL command help text

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wash-archive#142]
**Is your feature request related to a problem? Please describe.**
Typing commands in the REPL is intuitive, but scrolling the output pane, using the command history, and anything to do with the tui logger is opaque to the user.

**Describe the solution you'd like**
On the initial boot of the REPL, we can use the output window to display a form of help text. This help text would be different than appending `--help` to a command, instead it should essentially be a table of keys that do anything other than send input characters to the REPL input.

**Describe alternatives you've considered**
- An alternative is reserving the default `help` keyword, and perhaps that should also display the help text.
- Commands can be documented on wasmcloud.dev or in the README of this repository, but that would require users to know where to look.

**Additional context**
https://docs.rs/tui-logger/0.6.3/tui_logger/index.html#smart-widget-key-commands is the list of the tui logger key commands, this format could work as inspiration for our help text.

**Comment by autodidaddict** [comment]
Wash REPL is deprecated. Closing.
