### ISSUE TITLE
Issues with installing in windows using cargo

### ISSUE THREAD

**Issue by Aques** [wasmCloud/wash-archive#147]
I have tried intalling wasmCloud cli using cargo but issues of unresolved imports occurs. Kindly Help thank you
![14](https://user-images.githubusercontent.com/36673324/124393168-d7888700-dd16-11eb-9c3f-7b5256688712.PNG)
![15](https://user-images.githubusercontent.com/36673324/124393169-d8b9b400-dd16-11eb-8336-f2cac22610f1.PNG)
![1](https://user-images.githubusercontent.com/36673324/124393170-d9524a80-dd16-11eb-9d32-98055ceb760d.PNG)
![2](https://user-images.githubusercontent.com/36673324/124393171-d9eae100-dd16-11eb-9acf-4312a2f530dc.PNG)
![3](https://user-images.githubusercontent.com/36673324/124393172-d9eae100-dd16-11eb-9c72-cba1caf3ec20.PNG)
![4](https://user-images.githubusercontent.com/36673324/124393174-da837780-dd16-11eb-9560-7ab689d52ff2.PNG)
![5](https://user-images.githubusercontent.com/36673324/124393175-db1c0e00-dd16-11eb-85f4-5be2d5fdaddd.PNG)
![6](https://user-images.githubusercontent.com/36673324/124393176-dbb4a480-dd16-11eb-851c-5ce4cf414ab1.PNG)
![7](https://user-images.githubusercontent.com/36673324/124393177-dbb4a480-dd16-11eb-968a-c271fe4b6a4c.PNG)
![8](https://user-images.githubusercontent.com/36673324/124393178-dc4d3b00-dd16-11eb-9036-75ccdbaef78a.PNG)
![9](https://user-images.githubusercontent.com/36673324/124393179-dce5d180-dd16-11eb-8f85-3438a79db8c2.PNG)
![10](https://user-images.githubusercontent.com/36673324/124393182-dce5d180-dd16-11eb-993b-e04db2897658.PNG)
![11](https://user-images.githubusercontent.com/36673324/124393183-dd7e6800-dd16-11eb-98ce-54ca8f852a1b.PNG)
![12](https://user-images.githubusercontent.com/36673324/124393184-de16fe80-dd16-11eb-9351-0bb6aec34523.PNG)
![13](https://user-images.githubusercontent.com/36673324/124393185-de16fe80-dd16-11eb-83c2-e2b0826a4693.PNG)

**Comment by brooksmtownsend** [comment]
Hey @Aques, apologies for not seeing this issue earlier! This is unfortunately due to the terminal emulator (termion) not supporting Windows in their roadmap. This could be fixed relatively easily by making `termion` a default feature but optional, and Windows users would not be able to use the wash REPL. Is that the feature you are most interested in, or are you looking for wash as a whole?

Another option would be to completely replace termion with crossterm, which does have Windows support.

**Comment by Aques** [comment]
Thanks Brook for replying I was interested in using wash for some project
but was not able to do so because of these errors. I would try to make
termion optional or replace it with crossterm whichever works best. Thanks
again for your help.

**Comment by brooksmtownsend** [comment]
Hey @Aques , working on fixing this in my other PR #150. If you'd be willing to test, you should be able to install `wash` `0.5.0` now on your Windows machine with the following command:
```
cargo install --git https://github.com/wasmcloud/wash --branch 0.5.0-release --no-default-features
```
The `up` command will be missing, as `termion` is a requirement. You aren't missing out on too much, the REPL is going to be deprecated in `0.6.0` so it's not too far off of the norm 😄

**Comment by Aques** [comment]
Thanks Brook, I would be trying this one sorry was not able to reply soon
due to some work. Thanks for telling about details I will try this and tell
you how that works if possible 😁. Thanks again
