### ISSUE TITLE
Breaking changes for 0.6.0

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wash-archive#149]
To support the OTP runtime, things need to change for `wash` as well, an incomplete list of those changes that need to happen are below:

- [x] Ensure CTL topics are the same as what is used in the OTP runtime. I know some topics including the events have changed, but some have stayed the same.
- [x] Remove the REPL (no longer supporting the embedded wasmCloud host, the [wasmCloud dashboard](https://github.com/wasmCloud/wasmcloud-otp/tree/main/wasmcloud_host) should be used instead)
- [x] Support the new `wascap` feature of creating cluster keys (if not already supported)
- [x] Change the `wascap` standard capabilities to reflect the new builtin contracts `wasmcloud:builtin:logging` and `wasmcloud:builtin:extras` (being reviewed in https://github.com/wasmCloud/wascap/pull/36)

(from comments)

- [x] Ensure that RPC and RPC-related commands are moved to their own rpc sub-command and are no longer available on the ctl sub-command.
- [x] Support the ability for wash to read from 2 different sets of connection information so that it can talk to the RPC connection and control interface connection separately.
- [x] Support new linkdefs put and delete topics: `wasmbus.ctl.{prefix}.linkdefs.[del|put]` tracking linkdef del in https://github.com/wasmCloud/control-interface/issues/3
- [x] Move the `get.hosts` "query all hosts in the lattice" query to `ping.hosts`

**Comment by autodidaddict** [comment]
Per discussion with @brooksmtownsend : 

* Also need to ensure that RPC and RPC-related commands are moved to their own `rpc` sub-command and are no longer available on the `ctl` sub-command.
* support the ability for wash to read from 2 different sets of connection information so that it can talk to the RPC connection and control interface connection _separately_.

**Comment by brooksmtownsend** [comment]
Work is taking place in the following branch: ~https://github.com/wasmCloud/wash/tree/0.6.0-wasmcloud-otp~

edit: work is now taking place in https://github.com/wasmCloud/wash/tree/otp

**Comment by autodidaddict** [comment]
@brooksmtownsend @stevelr I added a couple more todos to handle things upcoming in my PR for JetStream support.
