### ISSUE TITLE
Extra auto-generated key created for Windows binaries

### ISSUE THREAD

**Issue by ChrisRx** [wasmCloud/wash-archive#16]
When using `wash par` to create a provider archive and not explicitly providing signing keys, wash will auto-generate keys based upon the binary filename passed in.  For example, `wash par insert --binary ./libwascc_fs.so` will create keys (if they do not already exist) named `libwascc_fs_{account,service}.nk`.  This becomes an issue when passing in a Windows binary since they do not contain the `lib` prefix as unix-like systems do.  So the above example for Windows will be `wash par insert --binary ./wascc_fs.dll` and will result in auto-generated keys for `wascc_fs_{account,service}.nk`.

This only matters when the keys are lazily created for the user, which seems to be mostly for development/testing.  However, it could be beneficial to base the auto-generated key name on something that will be consistent across platforms.  A naive solution might be simply trimming `lib` prefix.

**Comment by brooksmtownsend** [comment]
I'd like to do some thinking here on the best solution, I started to implement the `lib` prefix trim but I realized that you could have a capability provider that begins with `lib` (e.g. `liberizeSQL` (making that up, but it wouldn't surprise me)) and then we will be generating a key for `eriseSQL` for windows binaries. Ideally I'd like to utilize the Cargo project name, but I don't want to force people to be at the root of their cargo project to build `par` files. 🤔

**Comment by brooksmtownsend** [comment]
Trying this out on my own since this has sat here for a little bit, I can't reproduce this issue with windows binaries anymore. Feel free to re-open this issue though if you still can on a newer version of `wash`
