### ISSUE TITLE
Requiring a seed (signing key) for invoking actors

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wash-archive#168]
Cluster seeds are used to sign the anti-forgery tokens on invocations transmitted within the wasmCloud OTP host. As a result, in order for wash to be able to securely invoke actors without having said invocations rejected, wash will need to add a CLI option to the `call` command that lets the developer supply a cluster seed key.

This CLI option can default to the value found in the `WASMCLOUD_CLUSTER_SEED` environment variable. This makes it so that if they're using this variable for their OTP host configuration, then wash will automatically reuse that value and developers won't have to manually/explicitly supply a seed key.

**Comment by brooksmtownsend** [comment]
Fixed by #176
