### ISSUE TITLE
`wash new actor` should produce a makefile w/support for call aliases

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wash-archive#170]
The stock Makefile+actor.mk combination that we get from current emitted scaffolding doesn't support signing the module with a call alias. I'd like to be able to add an optional `CALL_ALIAS` field to my `Makefile` and then have `actor.mk` take care of that for me if I supply a value.

**Comment by autodidaddict** [comment]
Additionally, the `actor.mk` and `Makefile` combination should let me specify an alternate name for the actor. When signing the actor with the `--name "foo"` , the string inside the quotes can contain spaces and uppercase characters and is designed to let people provide a human readable name when you `wash claims inspect` the actor (or see the actor in a dashboard) 

For example, if my project name is `customers`, I should be able to set a name for the actor to something like `Kevin's Friendly Customers Actor` if I want.

**Comment by stevelr** [comment]
fixed in [project-templates](https://github.com/wasmCloud/project-templates/pull/16) and [examples](https://github.com/wasmCloud/examples/pull/88)
