### ISSUE TITLE
[BUG] wash reg push can't push to gcr.io

### ISSUE THREAD

**Issue by alsuren** [wasmCloud/wash-archive#187]
**Describe the bug**
`wash reg push` can't push to gcr.io

The underlying `oci-distribution` library doesn't seem to be compatible with something that gcr.io is doing
**To Reproduce**
```
$ wash reg push -u oauth2accesstoken -p "$(gcloud auth print-access-token)" eu.gcr.io/wasmcloud-k8s-demo/kvcounter:0.3.0 ./actor/kvcounter/build/kvcounter_s.wasm
⠍⠁  Pushing ./actor/kvcounter/build/kvcounter_s.wasm to eu.gcr.io/wasmcloud-k8s-demo/kvcounter:0.3.0 ...Error: An unexpected error occured: code=204 No Content, message=''
```

We managed to isolate where that error is coming from (the code is explicitly checking for an http 200 OK, but GCR is being pedantic and returning http 204 No Content). After we patched this to be more permissive, we ended up getting another failure further down the line and gave up. I will try to dig up my patch for the first bit if I get time today, but no promises.

**Expected behavior**
`wash reg push` should be able to push to gcr.io repos (this would make life easier for new open source projects, because it's easier to make these repos public)

**Environment (please complete the following information) **
 - OS: MacOS
 - Shell bash
 - wash Version 0.6.6

### Workaround

( from https://github.com/redbadger/wasmcloud-k8s-demo#readme )

We found some inconsistency when pushing and pulling images to and from GCR when using `wash cli`. We resorted to using `wasm-to-oci`. The inconsistency lied with the media types supported for the images. Had to change the supported media types within `wasm-to-oci` as shown below.

wash doesn't understand how to talk to gcr.io, and we're not in the mood for debugging it right now. As a work-around, we applied this patch to https://github.com/engineerd/wasm-to-oci :

```
diff --git a/pkg/oci/mediatypes.go b/pkg/oci/mediatypes.go
index 5c99816..ffaa489 100644
--- a/pkg/oci/mediatypes.go
+++ b/pkg/oci/mediatypes.go
@@ -2,5 +2,5 @@ package oci

 const (
        ConfigMediaType       = "application/vnd.wasm.config.v1+json"
-       ContentLayerMediaType = "application/vnd.wasm.content.layer.v1+wasm"
+       ContentLayerMediaType = "application/vnd.module.wasm.content.layer.v1+wasm"
 )
```

and push a new image like this `wasm-to-oci push todo-backend/target/wasm32-unknown-unknown/debug/todo_backend_s.wasm eu.gcr.io/wasmcloud-k8s-demo/todo-backend:0.2`

It may be possible to run `wasm-to-oci` with http logging turned on (or under wireshark/mitmproxy) and compare its http traffic log against what `wash reg push` does?

**Comment by brooksmtownsend** [comment]
partially Fixed by #257 , I believe an older update to `oci-distribution` fixed this 😄
