### ISSUE TITLE
[FEATURE] validation of `wash link put` arguments

### ISSUE THREAD

**Issue by alsuren** [wasmCloud/wash-archive#188]
**Is your feature request related to a problem? Please describe.**
it's really easy to mistype a contract id, or get the arguments to `wash ctl link put` mixed up, and put an id in there instead.

**Describe the solution you'd like**
It would be nice for wash to do some basic validation 
- [ ] force contract id to contain a `:`
- [ ] any contract id that starts `wasmcloud:` should match against a list of well-known first-party contract ids
  - [ ] maybe a flag to skip this validation if you're deploying a new capability provider on an old version of `wash`?

**Describe alternatives you've considered**
An alternative would be to avoid using positional arguments entirely, and force people to use option flags instead (this is the approach that the azure CLI takes, if my memory serves correctly). This would also avoid the problem that the `wash reg push` arguments are in a confusing order.

**Comment by brooksmtownsend** [comment]
This is definitely related to #192, and while we can't enforce any naming schemes for contract IDs we can certainly detect if a contract ID is a 56 character uppercase string of characters (likely an nkey) and issue a warning. I also don't mind the idea of using option flags only as long as it's easy to tell from the help text what's required and what's optional.

**Comment by brooksmtownsend** [comment]
If someone looks to work on this, we can do something very similar to #207 and @StuartHarris's work in #202 to validate that the `wash ctl link put` arguments are properly `<actor_id> <provider_id> <contract_id>`. Contract ID does not need to have a `:` in it, but we should be able to tell if the user puts in an nkey for the contract ID
