### ISSUE TITLE
Scrub GHA actions

### ISSUE THREAD

**Issue by jordan-rash** [wasmCloud/wash-archive#189]
I have noticed that the actions are using deprecated or out dated `uses:` stanzas.  Will use this issue to note them as I find them all

`release.yml`
https://github.com/wasmCloud/wash/blob/main/.github/workflows/release.yml#L23
https://github.com/wasmCloud/wash/blob/main/.github/workflows/release.yml#L36
https://github.com/wasmCloud/wash/blob/main/.github/workflows/release.yml#L50

**Comment by brooksmtownsend** [comment]
This looks like a great opportunity to upgrade the release actions to the standards in https://github.com/wasmCloud/wasmcloud-otp/blob/main/.github/workflows/wasmcloud_host.yml (which just happen to have been created later 😄 )

Looks like we mostly need to upgrade from `v1`s to `v2`s and use a more updated github release action
