### ISSUE TITLE
Autoincrement revision number upon signing

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wash-archive#191]
If a `wash claims sign` is performed without specifying a revision number, and a pre-existing output file has a non-zero revision number, then the final signed output product should have a revision number 1 higher than the previous output.

In other words, I've got a `Makefile` that builds to `build/myactor_s.wasm`. As long as my revision number is 0, it will continue to be zero for all builds. If I then manually sign the file and push it to `build/myactor_s.wasm` with a revision number of 1, then the _next_ time I run `make` the file will have a revision number of 2, and the next will be 3, etc.

Wash should emit something to stdout when such an auto-increment operation takes place.

**Comment by autodidaddict** [comment]
Come to think of it, I think a better approach might be to simply pass `--autorev` to wash during a claims sign. This way it doesn't need to have you do the manual step of creating the first non-zero revision number. With `--autorev` in place, the revision number will start at 1 and continue incrementing thereafter by examining the previously signed .wasm file. This produces the following sequence:
* `make` - revision 1
* `make` - revision 2
* ...

**Comment by autodidaddict** [comment]
:thinking: Wash would have to drop a file like `.revision` or something in the main repo directory because if someone were to check out a clean copy of the repository, we don't want them to start back over at revision 0.

**Comment by autodidaddict** [comment]
Further, what if there was a `.claims` file that contained the name, description, capabiltiies, and revision of the thing being signed. This would then let you just type `wash claims sign target/foo/foo.wasm -o build/foo_s.wasm` and all the other parameters are pulled from the `.claims` file, and if `--autorev` is supplied, wash can then modify the `.claims` file to contain the new revision.

**Comment by brooksmtownsend** [comment]
I think this gets into a complicated relationship with https://github.com/wasmCloud/wasmcloud-otp/pull/220 where, in my opinion, we could close this issue right now with the OTP host as you no longer need to worry about auto-incrementing the revision while you develop.

This does have the consequence that other hosts like the javascript host need to handle revisions in the same way. I'm pretty sure we resolved this conversation with the decision that using the `iat` value was the simplest solution to this problem without dealing with creating yet-another-config-file, and for the non-development feedback loop use case the `Makefile` will work.

Let me know what you think. cc @stevelr @thomastaylor312

**Comment by autodidaddict** [comment]
I agree this is outdated and doesn't make much sense now that a missing revision will have the host use the `iat` field.
