### ISSUE TITLE
[FEATURE] Give a hint for commonly mistaken inputs

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wash-archive#192]
**Is your feature request related to a problem? Please describe.**
Because we have a general idea about our inputs for wash, e.g. an actor ID, provider ID, and host ID should all be 56 character nkeys, we can give the user a warning if the input seems misshapen. Because command line tools have positional arguments it's also common for users to input arguments in the wrong order, we can detect if a nkey is provided in place of a contract ID, for example.

**Describe the solution you'd like**
We know the most about our inputs that are nkeys, and we should be able to provide warnings if the wrong key is provided (e.g. we expect an actor key, but we're provided with an nkey starting with VADK... which we know is a provider key)

We can also verify other inputs placed positonally around nkeys, for example if a contract ID is provided as a 56 character string, we can warn the user that it looks like an nkey (of course, it's just a warning, and if some user creates a 56 character contract ID that's fine)

**Comment by brooksmtownsend** [comment]
Thanks to #199 we got some great progress here. One other place we can build off of that PR is the cluster seed arg for `wash call`

**Comment by StuartHarris** [comment]
Oh yeah :-) forgot than one. Will add

**Comment by brooksmtownsend** [comment]
With the vast number of improvements in the linked PRs above, I'm marking this as complete. Thanks all for the contributions!
