### ISSUE TITLE
[FEATURE] Allow specific drain commands

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wash-archive#193]
**Is your feature request related to a problem? Please describe.**
`wash drain` currently has 4 options, `all`, `lib`, `oci`, `smithy`. These are useful for managing the cache collected by wasmCloud, but require you to clear many resources for each command.

**Describe the solution you'd like**
The bulk operations mentioned above are still useful, but for specific developer workflows the ability to remove a single resource from the cache, for example a single actor `wasm` or a single provider archive/binary.

I'm filing this feature request specifically to support our developer iteration loop with a `make update` command. Our ideal flow for automatically updating an actor while developing is:

1. Recompile the actor
2. Re-sign the actor to produce a new signed actor
3. Push the actor to the local registry
4. `wash drain X` where the argument is the actor ID, to remove it from the cache
5. issue a wash ctl update actor command to live update the actor

Eventually, we should be able to reproduce the same flow with providers, though that's a little more complicated due to the provider archive process.

The specific argument to `wash drain` will have to be determined. For actors, providing the OCI reference is the easiest, for providers it would be the public key. Ideally, you would be able to specify the same category of information (either OCI reference, name, or public key)

**Describe alternatives you've considered**
We've considered managing additional files with metadata about the project. Proposed solutions:
1. Continued management of information within `Makefile`
1. `.claims` or `.wasmcloud` which include version, revision, capability claims information
1. `.build_num` or `.revision` which include version and revision information, then using this to push to a new OCI reference (thus, avoiding the cache)

cc @stevelr @autodidaddict

**Comment by stevelr** [comment]
Using oci ref or public key are about the same level of difficulty for the user, if they are using our makefiles. Yet another possibility is the local file path, from which wash could get the public key.

I think I prefer the pub key as the arg for 'wash drain', because it's potentially more inclusive - in case you've been changing versions and you aren't sure which version(s) might be in the cache.
