### ISSUE TITLE
[BUG] delete link from wash doesn't work the same way as delete from washboard

### ISSUE THREAD

**Issue by stevelr** [wasmCloud/wash-archive#200]
**Describe the bug**
Seen while developing an event app.
wash ctl link del 
didn't seem to remove link from provider's list of links, because a subsequent link put resulted in error from provider "ignoring duplicate link"

May need some experimentation to reproduce.

**Comment by stevelr** [comment]
Not a bug - was using wrong params for link del. (provider id instead of contract id)

**Comment by brooksmtownsend** [comment]
This should be noted for #192, if you supply a 56 character uppercase contract ID we should warn the user
