### ISSUE TITLE
[FEATURE] add version command

### ISSUE THREAD

**Issue by ricochet** [wasmCloud/wash-archive#201]
**Is your feature request related to a problem? Please describe.**
No but it took me a minute to realize the version is printed with the normal `wash` command. I tried the usual suspects first: `wash -v`, `wash --version` and `wash version`.

**Describe the solution you'd like**
Implement any or all of the above version commands.

**Comment by ricochet** [comment]
User error. Looking back at my shell history, this is on me.

```bash
hello wash -version
error: Found argument '-v' which wasn't expected, or isn't valid in this context

USAGE:
    wash <SUBCOMMAND>

For more information try --help
➜  hello wash 00version
error: Found argument '00version' which wasn't expected, or isn't valid in this context

USAGE:
    wash <SUBCOMMAND>

For more information try --help
➜  hello wash version
error: Found argument 'version' which wasn't expected, or isn't valid in this context

USAGE:
    wash <SUBCOMMAND>
```

**Comment by brooksmtownsend** [comment]
Good ol' PEBKAC... glad it ended up working 😁
