### ISSUE TITLE
[BUG] <Issue> Wash ctl apply manifest need to applied twice to link

### ISSUE THREAD

**Issue by alanpoon** [wasmCloud/wash-archive#209]
Wash ctl apply manifest need to applied twice to link

**To Reproduce**
1. Run 'wash ctl apply  <manifest>'
2. wash says Link def submission is acknowledged
3. washcloud log says start provider and actor but does not say "linking"
4.  Run 'wash ctl apply  <manifest>' again
5. washcloud log says start actor and provider again, now says linking

**Expected behavior**
Linking happens when wash ctl apply  <manifest> first time

**Screenshots**
![image](https://user-images.githubusercontent.com/8205468/143973829-f35ab425-5a42-44e6-a288-bd551d544734.png)

**Environment (please complete the following information) **
 - OS:MacOS
 - bash
 - wash Version 0.7.1

**Comment by brooksmtownsend** [comment]
Hey @alanpoon, thanks for submitting this bug. What provider are you attempting to start in this example? I see the name of the executable is `wasmcloud_thread_default` which implies a new contract ID `wasmcloud:thread`. The host process will pass established link definitions to the capability providers on startup, so I want to ensure your provider is doing the same thing.

From the error text you supplied above, I can see a couple concerning NATS logs for failing to create a consumer, are you running `nats-server` with the `--jetstream` flag? If this isn't supplied, then the link definition would fail to be persisted in the lattice cache and the provider would only be able to receive it by being started before the link definition was published.

**Comment by brooksmtownsend** [comment]
@alanpoon would you mind providing a little more information on this issue? I can't tell exactly what needs to be done to fix this issue, and I'm not sure how to reproduce to see if it's related to https://github.com/wasmCloud/wasmcloud-otp/issues/361 or not.
