### ISSUE TITLE
[FEATURE] Add support for provider configuration

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wash-archive#212]
**Is your feature request related to a problem? Please describe.**
As seen in https://github.com/wasmCloud/control-interface-client/blob/main/src/lib.rs#L285, the control interface client now has support for provider configurations. This can be used, for example, to configure a provider with default link definition values, start a provider with a predefined instruction, etc.

**Describe the solution you'd like**
I'd like to see `wash` updated to `control-interface-client: v0.7.0` and implement provider configurations, which is an optional `String` value that can be supplied on the command line.

**Comment by ghost** [comment]
Is there an example for wha the provider configuration string looks like? is it JSON?

**Comment by ghost** [comment]
Oh, it looks like you implemented this already: https://github.com/wasmCloud/wash/blob/main/src/ctl/mod.rs#L359-L362. Did you want it as a String option as well or should we close this issue?

**Comment by brooksmtownsend** [comment]
Huh, looks like we did fix this! Good catch @mattwilkinsonn. Fixed in https://github.com/wasmCloud/wash/pull/236
