### ISSUE TITLE
[BUG] Auto key generation writes keys to disk as world readable

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/wash-archive#218]
**Describe the bug**
When using `wash key gen`, the keys written to disk have permissions of `644`, which means that anyone on the system can read them.

**To Reproduce**
1. Run a `wash claims sign` command to sign an actor or provider
1. Run `ls -la ~/.wash/keys` 
1. Observe the global read permission for the directory and generated key

**Expected behavior**
When generating keys, the permissions on *nix-like systems should be set to `600`. Also, when creating the directory for keys, that directory permission should be set to `700`.

**Environment (please complete the following information) **
 - OS: MacOS
 - Shell: zsh
 - wash Version: 0.7.1

**Comment by thomastaylor312** [comment]
Please note that for windows, it is real hard to manage permissions like this is Rust. The permissions logic will need to be separate for the different OS families anyway

**Comment by protochron** [comment]
I started working on this, and I'm done with the *nix side. Windows of course is a lot more difficult, since it looks like you need to call the Windows API directly using something like https://crates.io/crates/winapi.

**Comment by thomastaylor312** [comment]
Yeah, that sounds right. And even that API is a little unclear on what is the proper way to set permissions
