### ISSUE TITLE
[BUG] crash when using http:// before registry address

### ISSUE THREAD

**Issue by matsbror** [wasmCloud/wash-archive#219]
**Describe the bug**

**To Reproduce**
1. Start a local private registry
2. Push an actor or provider to the local registry
3. Use wash to ping the registry using http or https before the address

Eg.
```
wash reg ping --insecure http://localhost:5000/v2/fakepay_provider:0.1.0
```

**Expected behaviour**
Ok

**Actual behaviour**

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ReferenceInvalidFormat', /home/mats/.cargo/registry/src/github.com-1ecc6299db9ec823/wash-cli-0.7.2/src/reg.rs:276:44
```

**Environment (please complete the following information) **
 - OS: Linux/Ubuntu 20.04
 - Shell: bash
 - wash Version 0.7.2

**Comment by ghost** [comment]
OCI doesn't seem to support this from looking [the spec](https://github.com/opencontainers/distribution-spec/blob/main/spec.md).

Should just return a nicer error message?

**Comment by brooksmtownsend** [comment]
@mattwilkinsonn Exactly, we should just return a nicer error message indicating that the image reference failed to parse.
