### ISSUE TITLE
[BUG] JSON deserialization failure when retrieving host inventory

### ISSUE THREAD

**Issue by mydnicq** [wasmCloud/wash-archive#224]
**Describe the bug**
When executing `wash ctl get inventory <HOST_ID>`  the command exits with

`...Error: JSON deserialization failure: missing field 'instances' at line 1 column 188`

**To Reproduce**
1. Follow [Get started tutorial](https://wasmcloud.dev/overview/getting-started/)
2. After you add HTTP server capability provider run `wash ctl get inventory <HOST_ID>` as the tutorial suggests.
3. You'll get an error `...Error: JSON deserialization failure: missing field 'instances' at line 1 column 188`

**Expected behavior**
The command should report the host's inventory.

**Environment (please complete the following information) **
 - OS:  MacOS
 - Shell: zsh
 - wash Version: 0.7.2

**Comment by mydnicq** [comment]
I was using the wrong `wasmcloud_host` docker image. The image from the provided docker-compose has a tag `latest` but since I already had the `latest` image in my docker cache, `wash` executed the command against the wrong `host` version. This sounds almost like a local issue, however, to prevent similar issues in the future I've explicitly set `wasmcloud/wasmcloud_host` image to the desired version in the docker-compose file.

Maybe I've missed it, but is there a wash command to get what version has a particular host?

**Comment by brooksmtownsend** [comment]
@tadejstanic ATM there isn't a command to get the host version, though we could attach that as a label on the host 🤔 Your best bet is likely to access the dashboard and click the wasmcloud icon in the top right for now if you need the version
![image](https://user-images.githubusercontent.com/12040685/148089411-9eabbb04-bb9d-4dfa-994d-03b0bb5eba1c.png)
