### ISSUE TITLE
[FEATURE] Add scale actor command to wash ctl

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wash-archive#228]
**Is your feature request related to a problem? Please describe.**
The wasmCloud control interface supports the "scale" command for actors which allows idempotent scaling of actors to a desired count. See https://github.com/wasmCloud/control-interface-client/blob/main/src/lib.rs#L165 for the function definition or the docs for the structure https://docs.rs/wasmcloud-control-interface/latest/wasmcloud_control_interface/struct.ScaleActorCommand.html.

We should add a `wash ctl scale actor` command which allows scaling to a desired count.

**Comment by ghost** [comment]
Started prototyping this [here](https://github.com/mattwilkinsonn/wash/blob/scale-actor/src/ctl/mod.rs#L258-L276). My main question is what to do with the `annotations`. Is there any prior art on accepting key value input in wash? If not, what would be the best solution?

I could have the command just accept a JSON string and try to parse that with `serde_json`, or could have an interactive system asking for each key value pair. Perhaps both to support non-interactive and interactive contexts. Or could even have them pass in a JSON/YAML file. Any ideas on the best way to approach this?

**Comment by brooksmtownsend** [comment]
@mattwilkinsonn what we've done before is take in a `Vec<String>` and parse them according to a `key=value` syntax, there's a function in `util` you can use https://github.com/wasmCloud/wash/blob/main/src/util.rs#L129-L130
