### ISSUE TITLE
[BUG] Docker CI build failing on missing lib files

### ISSUE THREAD

**Issue by ghost** [wasmCloud/wash-archive#233]
**Describe the bug**

In the past few commits to `main`, the Docker CI jobs have all failed.

It appears the `rust:alpine` image is missing two files that our `Dockerfile` tries to copy over into the final image:

- /usr/lib/libcrypto.so.46
- /usr/lib/libssl.so.48

**To Reproduce**
1. Merge a PR into main.
2. Observe the failed Docker builds.

**Expected behavior**
The Docker builds not to fail due to missing files.

**Environment (please complete the following information)**
N/A, CI problem

**Additional context**
I tried pulling down the `rust:alpine` image we use, and then installed the packages from the first line of the Dockerfile:
`apk add --no-cache clang clang-dev libressl-dev ca-certificates musl-dev llvm-dev clang-libs curl gcompat`

When I enter the `/lib` directory these libs are present:
![Screen Shot 2022-01-22 at 3 15 57 PM](https://user-images.githubusercontent.com/28606055/150654083-a46b73ac-915c-406d-9f0a-6bbb9bd3c7f0.png)

It appears the ending number on `libcrypto` and `libssl` have changed to `.1.1` from `.46` and `.48` respectively. The dumb fix is to just change the file names, but then we'd just run into this problem again if another name changed.

**Comment by brooksmtownsend** [comment]
Thanks for submitting @mattwilkinsonn , yeah looks like I took the "dumb fix" route with #203 and we might be better off doing something more general. @jordan-rash is there a general way to fix this type of error for working with a scratch container?

**Comment by brooksmtownsend** [comment]
Edit: never mind, didn't see you submitted a fix as well! Thank you
