### ISSUE TITLE
[BUG] Updated Docker image deployment fails

### ISSUE THREAD

**Issue by ghost** [wasmCloud/wash-archive#241]
**Describe the bug**
#239 changed the Docker GitHub action to a new method using an Alpine image, but after merging into `main`, it is failing on a `permission denied` error.

**To Reproduce**
1. Merge a PR into `main`.
2. Observe failed Docker push.

**Expected behavior**
The push to DockerHub not to fail.

**Environment (please complete the following information) **
GitHub Actions

**Additional context**
Error from the action:
```
#20 ERROR: denied: requested access to the resource is denied
------
 > pushing wasmcloud/wash:alpine with docker:
------
error: denied: requested access to the resource is denied
Error: buildx failed with: error: denied: requested access to the resource is denied
```

[Link to failed action](https://github.com/wasmCloud/wash/runs/5308873592?check_suite_focus=true)

Also I could not be understanding the new action code but it looks like it is only pushing to DockerHub now, and also only pushing a `alpine` tag. Are we no longer pushing a `latest` tag or pushing to Azure?

**Comment by jordan-rash** [comment]
@brooksmtownsend I have not been successful in recreating this in my fork.  When I run the same action, it succeeds...I will have to check the action's issues and see if anyone else experiences this.

https://github.com/jordan-rash/wash/actions/runs/1889662615

The only difference in my action, is that I removed the Azure piece as I dont have access to a registry there.

**Comment by ghost** [comment]
> @brooksmtownsend I have not been successful in recreating this in my fork. When I run the same action, it succeeds...I will have to check the action's issues and see if anyone else experiences this.

When you run it in your fork, you aren't attempting to actually push the image right? That seems to be where the issue is coming up.

Also I saw that the Docker and Azure logins got swapped around in your PR, could that be causing an issue?

**Comment by jordan-rash** [comment]
I am pushing, but to [mine](https://hub.docker.com/r/cjrash/wash)....good catch on the switch, that was accidental.  I dont have a way to test it though...maybe @brooksmtownsend can test for me?

**Comment by brooksmtownsend** [comment]
@jordan-rash I can't see where credentials got swapped around, https://github.com/wasmCloud/wash/pull/239/files looks fine to me 🤔 If those were swapped though then it would certainly fail to authenticate

**Comment by ghost** [comment]
> @jordan-rash I can't see where credentials got swapped around, https://github.com/wasmCloud/wash/pull/239/files looks fine to me 🤔 If those were swapped though then it would certainly fail to authenticate

If you look at those changes, the action used to go Azure login and then Dockerhub login. The new one does the reverse. Perhaps the azure login action deletes the previous credentials?

**Comment by jordan-rash** [comment]
This is what I am thinking as well

**Comment by brooksmtownsend** [comment]
Wild. Okay let's swap the order and get a PR in

**Comment by brooksmtownsend** [comment]
I'll take a look

**Comment by brooksmtownsend** [comment]
my god https://github.com/wasmCloud/wash/runs/5413793973?check_suite_focus=true

**Comment by ghost** [comment]
No way lmao

**Comment by brooksmtownsend** [comment]
great catch @mattwilkinsonn, I can't believe that was the issue 😅
