### ISSUE TITLE
[BUG] wash ctl link put base64 padding character removal

### ISSUE THREAD

**Issue by emattiza** [wasmCloud/wash-archive#249]
**Describe the bug**
When parsing key value options provided to a link configuration, and a value contains `=`, the str.split function removes the `=` inside of the value token. This results in our base64 (which uses `=` as a padding character) config option failing to decode when supplied to the provider, and failing to start the link successfully. Applying the link and then echo'ing our base64 shows proper encode, but wash ctl link query shows a lack of '=' padding in the base64 value.

**Environment (please complete the following information) **
 - OS: Linux
 - bash
 - wash v0.10.0-alpha.1

**Additional context**
At issue is the split logic, which can be remedied through using splitn(2, '=') to parse pairs, and break on first `=` found, while leaving the value token remainder untouched. [See here](https://github.com/wasmCloud/wash/blob/52b61f91fc4fc49f62b039c956403a84eafb6ec9/src/util.rs#L133)

**Comment by brooksmtownsend** [comment]
closed by #250
