### ISSUE TITLE
[BUG] Installation on Fedora (35) is broken

### ISSUE THREAD

**Issue by rrichardson** [wasmCloud/wash-archive#260]
**Describe the bug**

The biggest issue is that once wasmCloud_core repo is configured on my system, it doesn't seem to contain the `wash` package. 
I'm not a yum expert, so I'm not sure how to best diagnose that. Presumably there just isn't a release for f35? 

Additionally,  there is no pygpgme package.  I installed it using `pip3` but the script doesn't detect that and the installation fails. 
Since that fails, it configures the yum repos to not do gpg checks, which means the repos won't be available, by default, to be utilized on an F35 system.  

After reconfiguring the repos to use gpg,  I was confident that my system was searching the wasmCloud repos, but it still failed to find wash. 

**To Reproduce**
1. Be massochistic enough to run Fedora 35
2. Run 
```
curl -s https://packagecloud.io/install/repositories/wasmcloud/core/script.rpm.sh | sudo bash
sudo dnf install wash
```

**Expected behavior**
I expected the `sudo dnf install wash` command to complete successfully and deliver a lovely binary for me to use. 

**Screenshots**
```
λ sudo dnf install wash
wasmCloud_core                                                                                                                                                                             5.4 kB/s | 3.9 kB     00:00
Importing GPG key 0x1E5DBC25:
 Userid     : "https://packagecloud.io/wasmCloud/wascc (https://packagecloud.io/docs#gpg_signing) <support@packagecloud.io>"
 Fingerprint: C20C 6434 A894 33B0 DA4B 1049 F91B 982D 1E5D BC25
 From       : https://packagecloud.io/wasmCloud/core/gpgkey
Is this ok [y/N]: y
wasmCloud_core                                                                                                                                                                             238  B/s | 296  B     00:01
No match for argument: wash
Error: Unable to find a match: wash
```

**Environment (please complete the following information) **
running zsh
```
λ uname -a
Linux ip-10-254-1-13.us-east-2.compute.internal 5.16.18-200.fc35.x86_64 #1 SMP PREEMPT Mon Mar 28 14:10:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Additional context**

**Comment by brooksmtownsend** [comment]
Interesting, I think we should have a release set for this. Let me see if I can reproduce 👍🏻 

In the meantime if you're looking to get it installed, once you have a Rust toolchain installed you can do `cargo install wash-cli` to get `wash`. That can get you unblocked in the short term 🙂

**Comment by rrichardson** [comment]
> cargo install wash-cli to get wash 

cargo install is my default choice.  I just figured I'd test the Fedora installation.  

I almost think that because of `cargo install`  I'm not sure if the `.rpm` is even necessary, since the installation instructions recommend installing Rust before `wash` 

I guess there might be enterprise customers who want to distribute `wash`  or there might be scenarios where people need `wash` but not Rust?  Not sure.

**Comment by brooksmtownsend** [comment]
<img width="149" alt="image" src="https://user-images.githubusercontent.com/12040685/167429054-6d5f37ff-13d5-4c65-8a4c-6e6a5dfb7d70.png">

This might be why... looks like we release up to Fedora 32 🙂 We'll just have to up that to newer versions of Fedora.

The deb/rpm instructions are something we'd like to be used as a default and then fallback to cargo, as of now we're integrating examples with TinyGo and AssemblyScript and we aren't going to require a Rust toolchain with additional language support

**Comment by brooksmtownsend** [comment]
https://packagecloud.io/docs#push_pkg will likely be useful for this, we just need to add in the additional OS numbers into the release_amd64 action matrix

**Comment by gmlewis** [comment]
Same situation for Linux Mint Cinnamon 20.3, by the way.

```bash
$ cat /etc/os-release
NAME="Linux Mint"
VERSION="20.3 (Una)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20.3"
VERSION_ID="20.3"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=una
UBUNTU_CODENAME=focal
```

**Comment by brooksmtownsend** [comment]
@gmlewis Thanks for bringing this to our attention too... we've got some planned improvements to the wash install process that _hopefully_ will remove our need to update packagecloud for each distribution.

For now, to install wash, a fallback you can always do is use a Rust installation and `cargo` to `cargo install wash-cli`

edit: Thank you for your patience!
