### ISSUE TITLE
[FEATURE] `wash up` / `wash start host`

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wash-archive#266]
Bring back `wash up`! A previous supported command in `0.18.0` that would launch a host in the integrated REPL. Though we've found that the REPL isn't the best experience for running a wasmCloud host, it would be great to have this command back again for a simple experience to start a host.

In tandem with #264, the first experience a developer would have with wasmcloud is
1. Look at documentation
2. Download `wash` for their respective OS/ARCH
3. Run `wash install`
4. Run `wash up`
5. Proceed with the example documentation

There are some edge cases to look out for, namely that we are going to either require that NATS is installed or accessible by the host.

**Comment by ghost** [comment]
Would `wash up` start NATS automatically if it isn't running?

**Comment by brooksmtownsend** [comment]
> Would `wash up` start NATS automatically if it isn't running?

I think that would be the best experience, we can always `warn` level log that we're starting NATS for the user. The balance is just between optimizing the initial developer experience and making sure that advanced use cases don't end up launching NATS accidentally when trying to connect to a remote cluster. For that use case, we should just check and see if the NATS connection succeeds to the URL and launch if not. If it's an issue then we could add a `--dont-launch-nats-please-and-error-out` flag 😄

**Comment by ghost** [comment]
> > Would `wash up` start NATS automatically if it isn't running?
> 
> I think that would be the best experience, we can always `warn` level log that we're starting NATS for the user. The balance is just between optimizing the initial developer experience and making sure that advanced use cases don't end up launching NATS accidentally when trying to connect to a remote cluster. For that use case, we should just check and see if the NATS connection succeeds to the URL and launch if not. If it's an issue then we could add a `--dont-launch-nats-please-and-error-out` flag 😄

Yeah I agree that's definitely the best UX experience. Is our eventual goal to get to a place where the average user doesn't care about NATS at all / doesn't need to know about it? That's what I was thinking anyway.

**Comment by brooksmtownsend** [comment]
> Is our eventual goal to get to a place where the average user doesn't care about NATS at all / doesn't need to know about it?

For the first 50% of using wasmCloud, yes! The user should get right down to writing some business logic and playing with wasmCloud. As soon as they get to deploying to prod and all they will have to think about NATS, but `wash` is all about making it easy to develop and get started
