### ISSUE TITLE
CLI should globally support JSON output

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wash-archive#28]
There should be a top-level flag that is supplied (possibly `--json` or `-j`) that switches between user-friendly output and automation-friendly (JSON) output. This lets the CLI be scriptable in many different ways, not the least of which allows the output to be further refined or interrogated with tools like `jq`.

**Comment by brooksmtownsend** [comment]
Big fan of this. As an addition, if we're working on scripting, it would be valuable to also accept the json output (for keys at least) as input for token creation and actor signing.

**Comment by autodidaddict** [comment]
Let's just make sure we don't hand-code something that can be done with `xargs` redirection. For example, you can call `wash` twice and use xargs to pump the output into another invocation's input

**Comment by brooksmtownsend** [comment]
Good point. I have a feeling some of these improvements are going to show up when we start some of this scripting
