### ISSUE TITLE
[BUG] Can't connect to `connect.ngs.global` using wash ctl

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wash-archive#283]
**Describe the bug**
When attempting to use an NGS credsfile to connect to connect.ngs.global, I get the following warning and error:
```
[2022-06-08T11:41:26Z WARN  rustls::conn] Sending fatal alert BadCertificate

presented server name type wasn't supported
```
**To Reproduce**
1. Get a set of credentials for `connect.ngs.global`
1. Run `wash ctl get hosts -r connect.ngs.global --ctl-credsfile <path/to/credsfile>`
1. See error

**Expected behavior**
I would expect, if given valid credentials, that we could connect through NGS just fine

**Additional context**
I've also been able to reproduce this error with a combination of `--ctl-seed` and `--ctl-jwt`

**Comment by jordan-rash** [comment]
Also seeing this!

**Comment by brooksmtownsend** [comment]
I asked about this in the NATS slack https://natsio.slack.com/archives/CLNJ3BQNB/p1654702878081809 just to get some clarity, I can reproduce this with the newest version of `async-nats` with just a simple binary
```rust
use std::time::Duration;
use tokio::runtime::Runtime;

fn main() {
    let runtime = Runtime::new().unwrap();
    runtime.block_on(async move {
        println!("Connecting...");
        let res = async_nats::ConnectOptions::with_credentials_file(
            "/Users/brooks/demo/leafnode/demo.creds".into(),
        )
        .await
        .unwrap()
        .connect("connect.ngs.global")
        .await;
        println!("Result: {:?}", res);
    });
    runtime.shutdown_timeout(Duration::from_millis(100));
}

```

Error:
```
Connecting...
Result: Err(Custom { kind: InvalidData, error: UnsupportedNameType })
```

**Comment by brooksmtownsend** [comment]
Depends on https://github.com/nats-io/nats.rs/pull/500 and then we simply need to follow the refactor guide from wasmbus-rpc to move to `async_nats`
