### ISSUE TITLE
[RFC] No more Makefiles

### ISSUE THREAD

**Issue by ghost** [wasmCloud/wash-archive#299]
**Is your feature request related to a problem? Please describe.**
With #297 solving the main use case of our current `Makefile` & `actor.mk` (building and signing actors), we can now look at removing the 'template' makefiles entirely. However there is a few useful commands in the current Makefiles that we will want to replicate directly inside `wash` before removing them entirely.

**Describe the solution you'd like**
Replicate all useful commands from the existing [actor.mk](https://github.com/wasmCloud/project-templates/blob/main/actor/hello/actor.mk) and [Makefile](https://github.com/wasmCloud/project-templates/blob/main/actor/hello/Makefile) direcly into `wash` itself, using `wasmcloud.toml` for whatever stored values are necessary. These include:

- `wash test` =>`cargo clippy --all-features --all-targets` & equivalent for go
- `wash push`=> `wash reg push {registry_url} {actor_file}`
- `wash start` =>`wash ctl start actor {registry_url} --timeout-ms 3000 {actor_ref}`
- `wash update` => `wash ctl update actor {host_id} {actor_id} {actor_ref}`
- `wash inventory` =>`wash ctl get inventory {host_id}`
- `wash clean` => `cargo clean && rm -rf build` & equivalent for go
- `wash inspect claims` => `wash claims inspect {actor_file}`
-  `wash actor-id` => Gets the actor's id from `claims inspect`.
- `wash host-id` => Get the first host's id from `ctl get hosts`.

Don't necessarily need all of these, comment if there's any we should drop, or if their names should change etc.

My hope with these is to
1. Delete the Makefiles entirely, which carries a number of benefits such as portability, simplicity, and a more 'polished' DX
2. Make the 'simple case' of developing wasmCloud applications (primarily actors for now, as those will be the most created) as easy as possible. IMO right now a lot of our `wash` commands are overly verbose, and the Makefile was an easy way around that, but we can do better directly inside `wash`.
3. Create more consistency between language toolchains and across template repos. The Makefiles between Rust and TinyGo already have some differences. The more languages/features/updates we have the worse that experience will get. Moving all of that functionality into `wash` and picking what toolchain to use based on the `wasmcloud.toml` config will remove this issue.

**Describe alternatives you've considered**

The only other option is to keep the Makefiles and not fold these commands into `wash`. I don't think this is a good idea due to all of the above.

**Comment by brooksmtownsend** [comment]
I agree wholeheartedly that we can improve our experience by making better use of `wash`, the first-class tool. I'm already a huge fan of `wash build`, and I've got some questions for the other ones.

I'm making an assumption that all of the braced values here are going to be present in the wasmcloud.toml, which I think you said just making it clear for the comments 😄 

- wash test =>cargo clippy --all-features --all-targets & equivalent for go
    - I like this as a first implementation and would love to extend this for specific integration tests later on (e.g. wash spins up a wasmcloud host for you, starts your actor, calls it, and exits)
- wash push=> wash reg push {registry_url} {actor_file}
    - Love this, really simple way to accomplish this goal.
- wash start =>wash ctl start actor {registry_url} --timeout-ms 3000 {actor_ref}
    - We could even enhance this by pushing if the actor isn't present in the registry. I'd also love to make this process not require the user to start a registry, but that can be a later enhancement
- wash update => wash ctl update actor {host_id} {actor_id} {actor_ref}
    - I don't think we should support this, only because host_id wouldn't be easy to put in the wasmcloud.toml file
- wash inventory =>wash ctl get inventory {host_id}
    - I don't think we should support this, only because host_id wouldn't be easy to put in the wasmcloud.toml file
- wash inspect claims => wash claims inspect {actor_file}
    - There has been some feedback that the verb + noun should be switched with `wash`, I would just want it to be consistent. I think ideally here you'd be able to `wash claims inspect` the same as you can today, but if you don't supply a file the fallback is the wasmcloud.toml

The concern I have for the next two is adding too many top-level subcommands, `wash` already has 14 subcommands 🤔 Perhaps these helpers could go under a subcommand that's built for retrieving information on a wasmcloud.toml supported project?
- wash actor-id => Gets the actor's id from claims inspect.
- wash host-id => Get the first host's id from ctl get hosts.

**Comment by ghost** [comment]
> I'm making an assumption that all of the braced values here are going to be present in the wasmcloud.toml, which I think you said just making it clear for the comments 😄

Yep, a lot of them already are. Things like host_id can change anytime though, so would probably just need to embed some kind of call to `ctl get hosts` to grab that.

> wash test =>cargo clippy --all-features --all-targets & equivalent for go
I like this as a first implementation and would love to extend this for specific integration tests later on (e.g. wash spins up a wasmcloud host for you, starts your actor, calls it, and exits)

Yeah that sounds great!

> wash start =>wash ctl start actor {registry_url} --timeout-ms 3000 {actor_ref}
We could even enhance this by pushing if the actor isn't present in the registry. I'd also love to make this process not require the user to start a registry, but that can be a later enhancement

Also sg. Maybe `wash start` just tries to start the actor assuming it already exists, but you could pass something like `--build` to automatically build/sign/push it.

> wash update => wash ctl update actor {host_id} {actor_id} {actor_ref}
I don't think we should support this, only because host_id wouldn't be easy to put in the wasmcloud.toml file

Talked about this a bit above, I think we can just embed a call to grab the host ids. If there is multiple can just make it an interactive selection of hosts

> wash inventory =>wash ctl get inventory {host_id}
I don't think we should support this, only because host_id wouldn't be easy to put in the wasmcloud.toml file

Same as above. Fine with getting rid of this one though if it's overkill, i was mainly just copying each command that already exists in the Makefile.

> wash inspect claims => wash claims inspect {actor_file}
There has been some feedback that the verb + noun should be switched with wash, I would just want it to be consistent. I think ideally here you'd be able to wash claims inspect the same as you can today, but if you don't supply a file the fallback is the wasmcloud.toml

Yeah, should definitely be consistent. I see that `claims inspect` is easier from a code management perspective but `inspect claims` is a little bit nicer DX-wise. IMO we should switch over to wash => verb => noun at some point, but i don't think it's as important as some of the other commands here. The `claims inspect` using wasmcloud.toml works for me!

> The concern I have for the next two is adding too many top-level subcommands, wash already has 14 subcommands 🤔

Yeah that's definitely a potential issue. I think that our problem right now is that wash's subcommand layout is based on simplicity from a code management perspective and not from a user of the CLI. Ideally i'd like to reduce the number of 3+ word commands (like `wash claims inspect` etc) and instead rely more on context and CLI flags to figure out what the user wants to do.

> Perhaps these helpers could go under a subcommand that's built for retrieving information on a wasmcloud.toml supported project?

IMO all wasmCloud projects should be a wasmcloud.toml project (in the near future). So then there shouldn't be a wasmcloud.toml specific subcommand. LMK your thoughts on this. 

I'm don't really mind about these commands, they just existed in the Makefile already, I was going for Makefile parity as much as possible. Maybe we do something like `wash get actor` `wash get host` which then prints out as much info as possible about the actor/host including the ID?
