### ISSUE TITLE
Allow manual purge of wasmCloud host caches

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wash-archive#31]
A command, perhaps `wash drain` (or just `drain` while inside `wash up`) should purge the caches used by the wasmCloud host in order to verify that you're getting the newest/most current bits from an OCI source. wasmCloud's caches are `TEMP_DIR/wasmcloudcache` and `TEMP_DIR/wasmcloud_ocicache` for the extruded PAR libraries and downloaded OCI binaries respectively.

**Comment by tiptop96** [comment]
Is this just a matter of removing all the files in said directories?

**Comment by autodidaddict** [comment]
Yes, each directory serves a different caching purpose, but `wash drain` should take a parameter that indicates whether we want to drain `all` of the local caches, or the `oci` caches or the `library` extracted cached files.

**Comment by tiptop96** [comment]
Great! 😊 I've begun working on this.

**Comment by brooksmtownsend** [comment]
Addressed by #78

**Comment by brooksmtownsend** [comment]
Fixed by #78
