### ISSUE TITLE
Support pluggable decoders

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wash-archive#32]
One thing that we've discovered while working on the `wash` CLI and, more specifically, the `up` REPL, is that we cannot provide contextual meaning to the output of actor function calls or provider calls. Because of the way MessagePack works, we cannot reliably determine how to decode the data without having some form of schema... coincidentally, this is exactly what we have with the [widl](https://github.com/wasmCloud/actor-interfaces) files that produce generated code for actors and providers alike.

Without a concrete decoder, we can't actually display the data coming from actors and providers. To address this, we should support the notion of `pluggable decoders`.  The following is one way in which this could work:

# [RFC] Flexible Plugins
Each plugin is a `waPC` module created in any of the languages we support for waPC widl generation. This module would accept incoming messages of type `PerformDecode` that would have the following fields:
* `namespace` - A namespace for the message. This corresponds _directly_ to the namespace of a given widl file
* `message_type` - The type of the message in need of decoding. Note that this is NOT the _operation name_, it is a discrete message type scoped to a namespace. Again, this corresponds directly to a data type that was generated from a widl pass.
* `format` - a numeric value indicating the format we'd like the data decoded in. (`1` = JSON, `2` = Debug/Human, for example)
* `payload` - the actual payload that we want decoded. This is a binary blob (byte array) containing the messagepack-encoded data.

This plugin (remember, it's "just a wapc module") then returns a `DecodeResponse` containing the following fields:
* `handled` - a boolean value indicating whether this plugin handled the request. A value of `false` here should be assumed to indicate that the module in question is _unaware_ of the data type requested. Anything executing said plugin should then move on to the next plugin in the chain to see if the next one can handle the decode request.
* `decoded_string` - A string that corresponds to the requested format containing the decoded value.

By allowing developers to simply drop wapc decoder modules into the `~/.wash` directory, we not only give people the automatic ability to decode first party messages (we can host a `coredecoder` module in our OCI and download it if it's not present), but we give consumers, developers, and even enterprise organizations the ability to generate "pretty-printers" for their respective data types. This even means they can customize them so that the decoded version of a message excludes PII/sensitive fields.

**Comment by brooksmtownsend** [comment]
From the data types that we generate via widl, can we generate a "basic" decoder module alongside the generated types? If that's not really in the scope of waPC code generation, I think a cargo template would suffice

**Comment by autodidaddict** [comment]
I think we should be able to generate nearly all of this, either with a scaffold/template or just by invoking the wapc code generator. What do you think @pkedy ?

**Comment by brooksmtownsend** [comment]
This was a great idea for improving the experience with `ctl call` and opaque msgpack blobs, but I think with the OTP runtime this is no longer relevant.
