### ISSUE TITLE
[BUG] `wash reg push` fails for registry URLs containing upper case letters

### ISSUE THREAD

**Issue by ChrisWhealy** [wasmCloud/wash-archive#323]
### Problem

The following `wash reg push` command fails with an obscure error message `invalid reference format`

```
$ wash reg push ghcr.io/ChrisWhealy/foo:0.1.0 build/foo_s.wasm

invalid reference format

Stack backtrace:
   0: anyhow::backtrace::capture::Backtrace::capture
   1: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
   2: wash::reg::handle_command::{{closure}}
   3: wash::main::{{closure}}
   4: std::thread::local::LocalKey<T>::with
   5: tokio::park::thread::CachedParkThread::block_on
   6: tokio::runtime::thread_pool::ThreadPool::block_on
   7: tokio::runtime::Runtime::block_on
   8: wash::main
   9: std::sys_common::backtrace::__rust_begin_short_backtrace
  10: std::rt::lang_start::{{closure}}
  11: std::rt::lang_start_internal
  12: _main
```

This is caused by a panic in the `oci-distribution` crate that does not accept upper case letters in the registry URL - in this case, caused by my GitHub userid being `ChrisWhealy` rather than `chriswhealy`

### Proposal

Given that the OCI specification specifically excludes the use of upper case characters, it would be very helpful if `wash` could ensure that registry URLs are always converted to lower case characters.  This avoids presenting the end user with an obscure error message that whilst correct, is meaningful only to that small subset of people with deep technical knowledge of OCI package deployment.

### Environment
 - OS: MacOS Monterey 12.3.1
 - Shell: `bash`
 - wash Version: `0.12.0`

**Comment by brooksmtownsend** [comment]
Just a note, this likely affects our generated github actions in [project-templates](https://github.com/wasmCloud/project-templates) so unless we patch this those templates should change too

**Comment by brooksmtownsend** [comment]
Wanted to circle back on this one because we tracked this down in the `oci-distribution` crate and this is actually _working as intended_. The official OCI spec does not allow for capital letters (as you mentioned) so the fix here is IMO to just `.to_ascii_lowercase()` the references. I'll take a look at fixing this one today because it's a small change but very annoying
