### ISSUE TITLE
`version` parameter in wasmcloud.toml should not be required

### ISSUE THREAD

**Issue by ghost** [wasmCloud/wash-archive#332]
Currently the `version` parameter in `wasmcloud.toml` is [required](https://github.com/wasmCloud/wash/blob/main/crates/wash-lib/src/parser/mod.rs#L177), which goes against the [mini-spec](https://github.com/wasmCloud/wash/issues/282#issuecomment-1145522739) i wrote in the wasmcloud.toml RFC. This should be changed to optional, and attempt to parse the language's config file version if not present. If the language does not offer a package version parameter (unlikely) and there's none provided in wasmcloud.toml then `wash build` should simply fail.

**Comment by brooksmtownsend** [comment]
@mattwilkinsonn I have a few questions
1. For our [project-templates](https://github.com/wasmCloud/project-templates) is the idea that we'd include `version` in the languages that need it, but not if we can parse the official toolchain's version?
2. If version is supplied in `wasmcloud.toml`, does that take precedence over the language config file? (the mini-spec reads like this)
3. What do you think of a basic `wash build --check` that validates that the config file is present, and could possibly print out the variables that the signed project would have? like:

```
$ wash build --check
validating project
it's good! your project is valid and it's a Rust actor!

NAME:      Foobar
VERSION:   0.1.0
CLAIMS:    wasmcloud:httpserver, wasmcloud:barbaz
```

3 is of course not required to fix this issue and probably would be a separate feature

**Comment by ghost** [comment]
@brooksmtownsend
> For our [project-templates](https://github.com/wasmCloud/project-templates) is the idea that we'd include version in the languages that need it, but not if we can parse the official toolchain's version?

Yep, that is my thinking! However, upon thinking about it more, I'd be pretty harshly against adding any language to the ecosystem that doesn't even have the ability to add version numbers. Even for something like Python we can just require wasmCloud Python projects to use `pyproject.toml`. Should still keep the wasmcloud.toml version number as a fallback option though.

> If version is supplied in wasmcloud.toml, does that take precedence over the language config file? (the mini-spec reads like this)

For wasmCloud purposes IMO yes. This is debatable though. We could print a warning to console if these don't match?

EDIT: clarifying my thoughts on this - In a scenario where the `version` parameter is optional in `wasmcloud.toml`, it being added is only useful in three cases (IMO, let me know if you think of another one):

1. Where a version number can't be provided in the language being used. See above, I think this would be bad anyways. Does anyone know a language where we can't require version numbers?
2. We haven't implemented parsing the version number for that language yet. This would always be temporary and generally an easy thing to add. We probably shouldn't move a language out of beta/early access (whatever we end up calling it lol) until this is added.
3. A user wants to override the version number provided in the language's config file.

In case 3, the wasmCloud version number should take precedent over the language's one, and this doesn't affect the other two cases.

> What do you think of a basic wash build --check that validates that the config file is present, and could possibly print out the variables that the signed project would have? like:

Yeah that looks great! Could be a great 'first issue' project.

**Comment by ghost** [comment]
Well i'm gonna eat my words I guess. Go doesn't have version number support? 🤯
