### ISSUE TITLE
[BUG] Cannot install wash on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by clin4** [wasmCloud/wash-archive#348]
**Describe the bug**
Cannot install wash on Ubuntu 22.04 LTS

**To Reproduce**
Run the scripts provided from the installation page for Ubuntu/Debian
curl -s https://packagecloud.io/install/repositories/wasmcloud/core/script.deb.sh | sudo bash
sudo apt install wash

**Expected behavior**
wash will be installed successfully

**Screenshots**
curl -s https://packagecloud.io/install/repositories/wasmcloud/core/script.deb.sh | sudo bash
sudo apt install wash
Detected operating system as Ubuntu/jammy.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Detected apt version as 2.4.5
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/wasmCloud_core.list...done.
Importing packagecloud gpg key... Packagecloud gpg key imported to /etc/apt/keyrings/wasmCloud_core-archive-keyring.gpg
done.
Running apt-get update... done.

The repository is setup! You can now install packages.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package wash

**Environment (please complete the following information) **
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04 LTS
Release:        22.04
Codename:       jammy

**Additional context**

**Comment by brooksmtownsend** [comment]
Hey @clin4 , you might find some additional help in #335, specifically around the recommendation to use `cargo` to `cargo install wash-cli`. This specific issue requires us adding jammy to our apt release list which we're currently looking into.
