### ISSUE TITLE
[BUG] wash claims sign fail, opcode 252

### ISSUE THREAD

**Issue by clin4** [wasmCloud/wash-archive#349]
**Describe the bug**
wash claims sign doens't work

**To Reproduce**
1.  create the hello actor via the command  wash new actor hello --template-name echo-tinygo
2.  try to run the make command and fail
3.  manualy sign it also fail

**Expected behavior**

**Screenshots**
from make
if not exist build mkdir build
tinygo build -o build/hello.wasm -target wasm -scheduler none -no-debug .
if not exist build mkdir build
echo build/hello.wasm
build/hello.wasm
wash claims sign build/hello.wasm --destination build/hello_s.wasm --name hello --http_server \
 \
-v 0.1.0

Wasm Element error: Unknown opcode 252
make: *** [Makefile:20: build/hello_s.wasm] Error 1

when manually run 
wash claims sign hello.wasm --destination hello_s.wasm --name hello --http_server -v 0.1.0
No keypair found in "/home/clin4/.wash/keys/clin4_account.nk".
                    We will generate one for you and place it there.
                    If you'd like to use alternative keys, you can supply them as a flag.

No keypair found in "/home/clin4/.wash/keys/hello_module.nk".
                    We will generate one for you and place it there.
                    If you'd like to use alternative keys, you can supply them as a flag.

Wasm Element error: Unknown opcode 252

**Environment (please complete the following information) **
 - windows 10, debian
 - bash, cmd
 - wash 0.14.0-alpha.1

**Additional context**

**Comment by brooksmtownsend** [comment]
@clin4 For now, unfortunately, we're restricted to Go 1.18 and TinyGo 23. We're currently working through a fix in the signing code that can properly handle unknown opcodes in https://github.com/wasmCloud/wascap/pull/39

**Comment by clin4** [comment]
Thank you very much! It really helps~. After fix the go and tinygo version, now it works~.  Do you know when the constraints will be removed? ( I was using  go 0.19 and tinygo 0.26 )
