### ISSUE TITLE
[BUG] failed to create an tinygo actor project

### ISSUE THREAD

**Issue by clin4** [wasmCloud/wash-archive#350]
**Describe the bug**
cannot create an actor project 

**To Reproduce**
1. wash new actor hello --template-name echo-tinygo 
2. I got No such file or directory (os error 2)
3. If I don't specify the template, it will show two templates and let me select, if I select the echo-tinygo, I will get the same error message.

**Expected behavior**

**Screenshots**
wash new actor hello --template-name echo-tinygo

No such file or directory (os error 2)
clin4@chen-wasm:~/wasm-code$ wash new actor hello 
✔ Select a project template: · echo-tinygo: a hello-world actor (in TinyGo) that responds over an http connection

No such file or directory (os error 2)

**Environment (please complete the following information) **
 - OS: debian
 - Shell: bash
 - wash 0.14.0-alpha.1
go version go1.19 linux/amd64
tinygo version 0.26.0 linux/amd64 (using go version go1.19 and LLVM version 14.0.0)

**Additional context**

**Comment by ghost** [comment]
Hi @clin4! Thank for the report!

Unfortunately I'm unable to reproduce this error, and the error message is not great :(

Would you be able to run the command with `RUST_BACKTRACE=1` set and send the stacktrace? Ex:
```
RUST_BACKTRACE=1 wash new actor hello --template-name echo-tinygo
```

**Comment by ghost** [comment]
I'm gonna close this issue for now as we're not able to take any actions on it at the moment. Feel free to reopen if you encounter this again or have a reproducible example!

**Comment by LennyPenny** [comment]
I was able to reproduce this using the snap version (wash 0.18.0-alpha.2) on a fresh fedora 38 install. Here is with the backtrace:

also happens with rust hello actor

>[lenny@fedora wasmupload]$ RUST_BACKTRACE=1 wash new actor hello --template-name echo-tinygo
🔧   Cloning template from repo wasmCloud/project-templates subfolder actor/echo-tinygo...
No such file or directory (os error 2)
Stack backtrace:
   0: wash_lib::generate::make_project::{{closure}}
   1: wash::main::{{closure}}
   2: tokio::runtime::park::CachedParkThread::block_on
   3: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
   4: tokio::runtime::runtime::Runtime::block_on
   5: wash::main
   6: std::sys_common::backtrace::__rust_begin_short_backtrace
   7: std::rt::lang_start::{{closure}}
   8: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:287:13
      std::panicking::try::do_call
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:487:40
      std::panicking::try
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:451:19
      std::panic::catch_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panic.rs:140:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:487:40
      std::panicking::try
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:451:19
      std::panic::catch_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panic.rs:140:14
      std::rt::lang_start_internal
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:148:20
   9: main
  10: __libc_start_main
  11: _start

**Comment by connorsmith256** [comment]
@LennyPenny do you have git installed on this OS? Like @mattwilkinsonn said, I'm surprised there's no context on the `No such file or directory (os error 2)` error. I wonder if this is happening where we spawn a process to set up a repo based off the template

**Comment by LennyPenny** [comment]
sorry for the late reply, but it's still happening even with git installed :(

![image](https://github.com/wasmCloud/wash/assets/4027243/8a94d7fb-d2e3-4b38-bca1-5567df4de324)

wash 0.18.0 installed from `cargo install`

**Comment by connorsmith256** [comment]
@LennyPenny I tried to reproduce from a fedora container, but could not 😕 Here are the steps I ran to set things up:

```
yum install git
```
```
curl -s https://packagecloud.io/install/repositories/wasmcloud/core/script.rpm.sh | sudo bash
sudo dnf install wash openssl
```

And then:
```
[root@537312adab00 /]# RUST_BACKTRACE=1 wash new actor hello --template-name echo-tinygo
🔧   Cloning template from repo wasmCloud/project-templates subfolder actor/echo-tinygo...
🔧   Using template subfolder actor/echo-tinygo...
🔧   Generating template...
✨   Done! New project created /hello

Project generated and is located at: /hello

Congratulations on installing wash!  Shell auto-complete is available. For instructions on setting up auto-complete for your shell, please see 'https://github.com/wasmCloud/wash/blob/main/Completions.md'
```

Here are the versions of things I used:
```
[root@537312adab00 /]# wash --version
wash 0.18.0
[root@537312adab00 /]# git --version
git version 2.40.1
[root@537312adab00 /]# cat /etc/fedora-release
Fedora release 38 (Thirty Eight)
```

Do you have any differences with your system?

**Comment by LennyPenny** [comment]
aah I figured it out! 

I installed via the `cargo install` route, not via dnf (as that was missing the builds before). This will not install the required native dependencies (https://github.com/wasmCloud/wash/blob/main/flake.nix#L70-L72)

So I had to install tinygo and protobuf manually. 

Probably best to add that to the readme

**Comment by connorsmith256** [comment]
Great suggestion! I filed issues to [update the wash README](https://github.com/wasmCloud/wasmCloud/issues/847) and our [documentation](https://github.com/wasmCloud/wasmcloud.com-dev/issues/113) to include this information
