### ISSUE TITLE
[BUG] Comments Cause Make, Wash Lint and Validate to Fail if Placed Below Attribute Tag

### ISSUE THREAD

**Issue by andar1an** [wasmCloud/wash-archive#351]
**Describe the bug**
No Error: 
```
@n(0)
@required
fieldName
```
Error:
```
@n(0)
// comment
@required
fieldName
```
Error:
```
@n(0)
@required
// comment
fieldName
```

**To Reproduce**
1. Create an interface 
2. Within a structure, copy one of the error blocks above. 
3.  Run Wash Lint or Make

**Expected behavior**
Comments should not cause an error.  If this is expected behavior, and a comment should not be placed below an attribute tag, is it documented? 

**Environment (please complete the following information) **
 - OS: 5.15.78-1-MANJARO
 - Shell zsh
 - wash Version 0.13.0

**Comment by stevelr** [comment]
I agree it's non-intuitive, since in rust you can mix the order of macros and doc comments.  This rule makes it easier one for the smithy parser to distinguish between general comments in the file and comments associated with an item.  

The parser is working in agreement with the [Smithy 1.0 specification](https://smithy.io/1.0/spec/core/idl.html#comments)

> documentation comments MUST appear before any traits applied to the shape in order for the documentation to be applied to a shape.

While we can't easily change the smithy spec, we do want the developer experience to be good, and it should never be a requirement that every developer is intimately familiar with a detailed spec. Just as with a programming language syntax error, we would want error messages that tell the developer exactly what the problem is, so they learn the rules and can fix problems quickly.

If the error messages were incomplete or misleading we'd appreciate suggestions for improving them.

**Comment by andar1an** [comment]
I think a clear indication that there can't be a comment below a Smithy trait would be all that was required. 
Below are error messages I experienced from Wash Lint and Make. The Wash Lint error at least makes it easy to see what is wrong, but not why. If there is some way to indicate in an error that a comment can't be below a Smithy trait, that would be much more clear for these occurrences. 

Wash Lint Error: 
```
smithy error: assembling model: Error(
    Deserialization(
        "Smithy IDL",
        "pest",
        None,
    ),
    State {
        next_error: Some(
            Error {
                variant: ParsingError {
                    positives: [
                        identifier,
                        a_trait,
                    ],
                    negatives: [],
                },
                location: Pos(
                    1645,
                ),
                line_col: Pos(
                    (
                        55,
                        3,
                    ),
                ),
                path: None,
                line: "  /// indication whether the request was successful",
                continued_line: None,
            },
        ),
        backtrace: InternalBacktrace {
            backtrace: None,
        },
    },
)
```
Make Error: 
```
error: failed to run custom build command for `jammin_interface_music_auth v0.1.0 (/home/stephen/Repos/Jammin_Prototype/interface/jammin_interface_music_auth/rust)`

Caused by:
  process didn't exit successfully: `/home/stephen/Repos/Jammin_Prototype/interface/jammin_interface_music_auth/rust/target/debug/build/jammin_interface_music_auth-aec7c1aa355a97e3/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=/home/stephen/Repos/Jammin_Prototype/interface/jammin_interface_music_auth/codegen.toml

  --- stderr
  Error: Model("assembling model: Error(\n    Deserialization(\n        \"Smithy IDL\",\n        \"pest\",\n        None,\n    ),\n    State {\n        next_error: Some(\n            Error {\n                variant: ParsingError {\n                    positives: [\n                        identifier,\n                        a_trait,\n                    ],\n                    negatives: [],\n                },\n                location: Pos(\n                    1645,\n                ),\n                line_col: Pos(\n                    (\n                        55,\n                        3,\n                    ),\n                ),\n                path: None,\n                line: \"  /// indication whether the request was successful\",\n                continued_line: None,\n            },\n        ),\n        backtrace: InternalBacktrace {\n            backtrace: None,\n        },\n    },\n)")
make: *** [interface.mk:45: all] Error 101
```
