### ISSUE TITLE
[FEATURE] Bump wascap to 0.9.0

### ISSUE THREAD

**Issue by jordan-rash** [wasmCloud/wash-archive#357]
**Is your feature request related to a problem? Please describe.**
my tinygoz needs this....

**Describe the solution you'd like**
bump wash to wascap 0.9.0

**Describe alternatives you've considered**
learning rust 🤮 

**Additional context**
It seems you have sneakily [fixed my problem](https://github.com/wasmCloud/wascap/pull/39)....merry christmas to me 💃🏼 

> The parity-wasm crate, even the newest version, fails to parse "modern" WASI modules produced by TinyGo and other languages (the infamous "unknown opcode" error).

**Comment by brooksmtownsend** [comment]
completed after #361 ! This will go into alpha versions of wash but modules signed in this way will _only_ be compatible with wasmCloud hosts on version 0.60.0 or later.

**Comment by jordan-rash** [comment]
👯‍♀️
