### ISSUE TITLE
[BUG] `wash up` requires workaround with machines running OpenSSL 3.0 for libcrypto1.1

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wash-archive#366]
The fix for this is being tracked in https://github.com/wasmCloud/wasmcloud-otp/issues/413, but this issue details a workaround. 

**Describe the bug**
On newer linux distributions like Ubuntu 22.04, OpenSSL 3.0 is included by default and the shared libraries for libcrypto are not present with the versions wasmCloud expects. This results in a fairly nasty stacktrace when running `wash up`:
```
"Failed to load NIF library /root/.wash/downloads/lib/crypto-5.0.6/priv/lib/crypto: 'libcrypto.so.1.1: cannot open shared object file: No such file or directory'"}}}}},
             {kernel,start,[normal,[]]}}
    type: permanent

Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,crypto,{error,{load_failed,"Failed to load NIF library /root/.wash/downloads/lib/crypto-5.0.6/priv/lib/crypto: 'libcrypto.so.1.1: cannot open shared object file: No such file or directory'"}}}}},{kernel,start,[normal,[]]}}})
```

If you see this error, you can follow the steps below to remediate for arm64 and amd64 architectures, respectively. In order to get past this you can install the libssl1.1 compatibility layer and `wash up` will work just fine.

For arm64 machines, you can run the following to install wash (you may need to pipe into `sudo bash` for packagecloud):
```
apt update; apt install curl -y
curl -s https://packagecloud.io/install/repositories/wasmcloud/core/script.deb.sh | bash
apt install wash
curl -fLO http://ftp.us.debian.org/debian/pool/main/o/openssl/libssl1.1_1.1.1n-0+deb11u3_arm64.deb
dpkg -i libssl1.1_1.1.1n-0+deb11u3_arm64.deb
wash --help
```

And for amd64 machines:
```
apt update; apt install wget -y
wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.17_amd64.deb
sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.17_amd64.deb
curl -s https://packagecloud.io/install/repositories/wasmcloud/core/script.deb.sh | bash
apt install wash
```

Alternatively, or if the above doesn't work for you since you're not using debian, you can build openssl from source:
```
apt update
apt upgrade
apt install curl build-essential pkg-config libz-dev -y
curl -s https://packagecloud.io/install/repositories/wasmcloud/core/script.deb.sh | sudo bash
sudo apt install wash
curl -fLO https://www.openssl.org/source/openssl-1.1.1s.tar.gz
tar -xvf openssl-1.1.1s.tar.gz 
cd openssl-1.1.1s
./config --prefix=/usr/local/ssl --openssldir=/usr/local/ssl shared zlib
make
make test
make install
```

**Comment by brooksmtownsend** [comment]
This will be closed very soon! #556 will fix this

**Comment by aschrijver** [comment]
```
wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.17_amd64.deb
```

404 Not Found.

I started searching for an alternative location, only to find how [bad of an idea](https://askubuntu.com/a/1412746/1625817) fiddling with `openssl` is. Which, not being an expert, it _feels_ like too.

Any indicator on the "closed very soon"? I may wait till then before installing wash / wasmCloud.

**Comment by brooksmtownsend** [comment]
Hey @aschrijver thanks for the ping, yeah I saw that package update versions before so it just needed to be updated.

What this issue suggests is installing a compatibility library, and I agree that it feels volatile to fiddle with OpenSSL. One thing you can always do to try out wasmCloud is use the codespace in this repository, which will let you get started without a local install (codespaces are free for open source!)

"soon" got a lot longer because I've been on vacation for the last two weeks, but it's a priority for me now that I'm back :)

**Comment by brooksmtownsend** [comment]
As of `v0.18.0`, this is closed! @aschrijver you're now free to get started without dealing with this 😄

**Comment by aschrijver** [comment]
Wonderful, thank you! I did the Rust build and subsequently the Concordance banking example. That went all smooth as well, but I'll now use the regular install.
