### ISSUE TITLE
[BUG] Control interface and context commands fail without a host config

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wash-archive#371]
**Describe the bug**
On a fresh `wash` machine, with no `~/.wash/host_config.json` file, any control interface command fails with `No such file or directory`. I thought this was because I was failing to connect to NATS, but it turns out that `wash ctx` commands also fail. I assume this is because we're attempting to form a control client based on those values, but we should be able to gracefully handle a host_config that doesn't exist.

**To Reproduce**
1. `rm ~/.wash/host_config.json`
2. Run any control interface command

**To Workaround**
All you need is a valid `host_config.json`, so running the following commands will allow you to start with default values.
```
wash ctx new host_config; cp ~/.wash/contexts/host_config.json ~/.wash/host_config.json
```

**Comment by ghost** [comment]
Hm. I can successfully start actors even when i remove that file and delete all `wash ctx` entries. And if I nuke the whole `.wash` folder I can still start them 😂

I don't think that's intended behavior either though so looking into it

**Comment by brooksmtownsend** [comment]
What version of `wash` are you on @mattwilkinsonn ? It might be an issue with `0.14.0`

**Comment by jordan-rash** [comment]
@brooksmtownsend I think you need to check your "workaround"

`wash ctx new host_config.json` creates file `host_config.json.json`

So I think it just needs to be `wash ctx new host_config`

**Comment by brooksmtownsend** [comment]
Great catch @jordan-rash, fixed ❤️
