### ISSUE TITLE
[FEATURE] More generic templates for `wash new`

### ISSUE THREAD

**Issue by protochron** [wasmCloud/wash-archive#373]
**Is your feature request related to a problem? Please describe.**
If you're starting a new project with `wash new`, you have to select from a set list of pre-built templates. That works well enough if you're just starting out with wasmcloud, but if you're a more advanced user then you're forced to instantiate a template based on contracts you may or may not need and then have to delete code before you're ready to kick off work on your project.

**Describe the solution you'd like**
A minimal template for actors and providers that bootstraps the makefiles, etc. but that's it. We can either have that come in as a dedicated template to select from or possibly a command line flag (`--minimal-template`?)

**Comment by ghost** [comment]
`--minimal-template` sounds nice but I don't want to be Rust-biased 😂

How about `--minimal-rust`?

**Comment by ghost** [comment]
Hmm I'm not actually as sure about what the minimal template should be. Looking at the [echo](https://github.com/wasmCloud/project-templates/tree/main/actor/echo) and and [echo-messaging](https://github.com/wasmCloud/project-templates/tree/main/actor/echo-messaging) templates, there's 4 things you need to change:
- the claims in `wasmcloud.toml`
- the claims in the `Makefile` (hope we can remove this eventually)
- remove `wasmcloud-interface-httpserver`/ `wasmcloud_interface_messaging` from `Cargo.toml` 
- remove the `httpserver` / `messaging` import from `src/lib.rs` and delete the `impl` block

But in all these places you need to replace the existing config/code with what you want to write anyways. I'm not sure how useful it is to remove these and just have a 5 line `lib.rs` file and no claims. Maybe the README or CLI output could list these to tell the user exactly where they need to go to get started?

EDIT: woops, that close was a misclick 😂

**Comment by stevelr** [comment]
We don't need another flag for `wash new`: I think @protochron 's request can be achieved by creating a minimal template. Then you can use `wash new actor -t bare-minimum`
There's also a `--values` flag that can load a file of parameters to be used when generating the project. So you could write a shell script that wraps `wash new` that accepts a contract name as a parameter, generates the values file, and then generates a project for that contract based on the 'minimal' template, merged with the values.
