### ISSUE TITLE
[FEATURE] wash ctl get should also output the lattice prefix

### ISSUE THREAD

**Issue by protochron** [wasmCloud/wash-archive#377]
**Is your feature request related to a problem? Please describe.**
I've hit this a number of times, but if you happen to be using the wrong lattice prefix `wash ctl get hosts` just tells you there aren't any hosts. This is easy to spot if you happen to remember that you need to be using the correct lattice prefix, but I think we can make this sort of thing easier to spot.

**Describe the solution you'd like**
We should emit the lattice prefix on any `wash ctl get` invocation to make it more obvious that you're querying for information against a specific lattice. While you _can_ also get that info if you get the JSON output from any get command, that isn't necessarily as friendly.

**Comment by connorsmith256** [comment]
I wonder if there's a more general solution, since I've run into this specific case as well as others, e.g. I had the wrong server hostname/port. 

Mismatched lattice prefixes might be the most common, but this can happen for any wash context setting where the current context isn't what you think it is 🤔

**Comment by brooksmtownsend** [comment]
I think we specifically hit this with something else, link name maybe, for `ctl link put`. I like the idea of adding another field into the spinner (as long as that persists after the command runs) for something like `Getting hosts for lattice 'default'` or similar

**Comment by brooksmtownsend** [comment]
<img width="337" alt="image" src="https://user-images.githubusercontent.com/12040685/216349872-a6fe50aa-45a8-4786-90ca-775b0b47732a.png">

This is what we show now, so `Retrieving hosts from lattice 'default'` could work! The spinner doesn't stick around though, so you would have to snipe the spinner text or we could do a println

**Comment by connorsmith256** [comment]
I like this idea. It's a simple change and will help the most common case 👍
