### ISSUE TITLE
Support all wash commands in REPL

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wash-archive#38]
At the time of writing this issue the REPl is focused on providing a fast feedback & development environment for wasmCloud developers. All of the command interface (`ctl`) commands are supported in the REPL currently, making the current state of the REPL primarily a command interface tool.

`wash up` is a separate command from `ctl`, and it should support all `wash` operations (e.g. `claims`, `keys`, `par` ...) in order to provide a fully featured REPL for the cli. There are some complications that come with this, like needing to pay attention to where you are in the local filesystem (at least a `pwd` equivalent would be necessary).

Because `wash up` re-uses the StructOpt structs from the `ctl` module, the same can be done for the other modules so there should not be large re-uses of code to implement this.

**Comment by tiptop96** [comment]
I took the liberty of looking at this and thought I would start with the `claims` related commands: `sign`, `inspect` and `token`. I found that for rendering the result of `inspect` I can render them as the classic table (aka `OutputKind::Text`) generated by `render_actor_claims` inside the REPL output window. However I am not sure if this is desired. Would a simple `key: value` output be better?

I guess the same question would apply to `par inspect` later down the road.

Let me know if there is anything else I should keep in mind. 😄

**Comment by brooksmtownsend** [comment]
I think ideally we'd like for as much useful information in as little space as possible for the REPL output window

I tried to manually format things for the get commands which ended up being too difficult and hacky. The solution I ended up doing was just customizing the term-table to be a simple table with unseparated rows (You should be able to see those examples in src/ctl.rs). Definitely open to a more efficient output format, but at the end of the day a pub key + OCI reference ends up being a long row 😄 

Thanks for looking at this! Feel free to check in with progress

**Comment by tiptop96** [comment]
Awsome, are the `claims_table`, `hosts_table` and `host_inventory_table` functions in src/ctl.rs the ones you are talking about?

Thanks, I will check in when I have draft for the `claims` related work, make sure that I'm moving in the right direction 😄

**Comment by brooksmtownsend** [comment]
Those are the ones! And I think it would be good to have claims and keys have the same table type as ctl anyways, so it's good to model the style from that

**Comment by brooksmtownsend** [comment]
Closed by #48 💯
