### ISSUE TITLE
[BUG] Building actor with Wash 0.14.1 causes claims error

### ISSUE THREAD

**Issue by andar1an** [wasmCloud/wash-archive#380]
**Describe the bug**
When trying to build actor with Wash 0.14.1, either claims not found in source module, or give error about "can't pull latest tag" even if using SemVer and not a string tag (tried 0.0.1 version and "dev" version. 

**To Reproduce**
1. Run command 'wash build' for actor with v0.14.1
1. Run other command 'wash claims inspect actor_name.wasm'
1. repeat above steps with wash 0.14.0

**Expected behavior**
Builds, and then inspection shows no errors about claims in the source module, or errors about pulling the latest version

**Comment by brooksmtownsend** [comment]
@stephenandary I'm a little unclear about this issue, would you mind restating some of the reproduction steps here? Is the actor failing to build, or is `wash` failing to inspect claims of a module?

**Comment by andar1an** [comment]
The actor builds, but when you inspect the actor you will see no claims, even if they should exist. I updated above

**Comment by connorsmith256** [comment]
Using wash built from main (as of writing, the same commit as tag v0.14.1), I'm able to successfully compile and inspect claims for an actor I generated with the same version of wash. @stephenandary I think we need a minimal reproducible example

**Comment by andar1an** [comment]
You can try adding a custom interface claim which would be the only difference an example would show.

**Comment by brooksmtownsend** [comment]
@stephenandary I'm not quite sure what this issue is referring to and it's starting to go stale so I'm going to close it. Let us know if this is still happening
