### ISSUE TITLE
[FEATURE???] Remove the binary and arch requirement from `wash par create`

### ISSUE THREAD

**Issue by jordan-rash** [wasmCloud/wash-archive#387]
**Is your feature request related to a problem? Please describe.**
When programmatically creating a provider, it would be easier to do something like 
```
╰─❯ wash par create --name derp --capid derp:foo --vendor awesomesauce --compress
```

And then add the binaries one at a time via the `wash par insert`

At the moment, `wash par create` requires an architecture and a binary.  I suggest we make these optional

**Describe the solution you'd like**
```
╰─❯ wash par create --name derp --capid derp:foo --vendor awesomesauce --compress
// Empty provider archive created
╰─❯ wash par insert -a x86_64-darwin -b mybinary derp.par.gz
    ...
    ...
    ...
```

**Describe alternatives you've considered**
At the moment, the archive has to be created with one of the provider binaries, which isn't the worst, just makes scripting harder

**Comment by brooksmtownsend** [comment]
@jordan-rash I like this idea, so you could create an empty provider archive after this 🤔 It might require some changes to the provider-archive crate to actually support that use case. I do think we could make it optional as you mentioned and so it wouldn't break any existing actions, just would support new use cases!

**Comment by jordan-rash** [comment]
YAY!

**Comment by jordan-rash** [comment]
Maybe this can be added to the wash refactor??
cc: @connorsmith256
