### ISSUE TITLE
Should `wash down` only stop the processes that `wash up` started?

### ISSUE THREAD

**Issue by ghost** [wasmCloud/wash-archive#402]
See #398 for some background context.

The question is, should `wash down` be able to figure out what exactly `wash up` started (in particular, if it started NATS or just simply connected to it) and only take down what `up` started. A user would probably say yes? But then we introduce a state problem that isn't easy to guarantee will always work correctly.

Some quick ideas:
- Write to a file containing the PID of processes we started
  - What happens if that process is killed by other means/the user reboots?
- Is there any kind of "tagging" mechanism on processes we can use?

**Comment by jordan-rash** [comment]
> A user would probably say yes?

FFIW, I would be very upset if some tool I used was killing off services it didn't start.  

`wash down` should 💯 be scoped to only PIDs it starts

**Comment by connorsmith256** [comment]
Agreed with Jordan. Using a PID-file doesn't feel elegant, but it's straightforward. If no process is alive with an ID matching the contents of the file, that's fine; just assume the user/system has already killed the process

**Comment by thomastaylor312** [comment]
Thirded (yes I invented that word). Most people do get annoyed when something kills it shouldn't

**Comment by thomastaylor312** [comment]
Yep, I just ran into this when writing tests for wadm. We should definitely make sure we only do stuff to NATS we've started

**Comment by brooksmtownsend** [comment]
This is the way as it is implemented in #556, and it is the way.
![tenor-111641029](https://github.com/wasmCloud/wash/assets/12040685/7296e058-8216-49dd-96a3-ed690232a84e)
