### ISSUE TITLE
Ensure test resources get cleaned up from integration tests, and don't use `defer!` to do it

### ISSUE THREAD

**Issue by ghost** [wasmCloud/wash-archive#405]
From discussion on #397, we should make sure all integration tests clean up their resources before (or when) exiting to not cause flaky failures in other tests. #395 also accomplishes this to some extent by using the `tempfile::TempDir` struct for test directories.

The "quick and dirty" approach to this is to use a `defer!` macro to run some code before the test exists, regardless if it panic'ed or not. This is a bit of a code smell though, 1. because it's a macro and 2. you could simply forget to use it or update the existing one when making changes. We should prefer to use `tempfile::TempDir` or a custom type with a custom `Drop` implementation. However given our flakiness situation I'm preferring `defer!` for now, and then will move to the better approach in follow up refactors.

**Comment by thomastaylor312** [comment]
One suggestion is to create a cleanup guard that can call `wash down` for us. I did a similar pattern with that here: https://github.com/wasmCloud/examples/blob/1ce69e6371826a0395d345c78f9ab43901f000be/actor/blobby/testing/tests/setup.rs#L15
