### ISSUE TITLE
par inspect does not output revision and version

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wash-archive#42]
`wash par inspect` is a way of inspecting a provider archive and printing the contents of the embedded claims to stdout in a human readable format (or, after #39, potentially as json)

The claims information displayed does not include revision or version information, which is invaluable for identifying the correct version of a parJEEzy to use. In order to implement this, one should just need to add additional rows to the table if `rev` and `ver` information is present on the claims.

**Comment by tiptop96** [comment]
I could give this a shot in a few hours. 👍

**Comment by brooksmtownsend** [comment]
Sounds great @tiptop96! 🔥

**Comment by brooksmtownsend** [comment]
Fixed by #45
