### ISSUE TITLE
[BUG] 'Validate' and/or 'Lint' on Smithy templates does not catch reserved words

### ISSUE THREAD

**Issue by cauldnz** [wasmCloud/wash-archive#436]
**Describe the bug**
If certain Rust reserved words are used as part of the Smithy interface definition, the generated Rust code will fail to compile.
This failure occurs even though the interface definition passes both `lint` and `validate` checks in `wash`.

**To Reproduce**
1. Run command 'wash new interface'
2. Create new actor to service interface per Docs
3. Run `make` which succeeds
4. Create the following type within that interface. This type uses a reserved word `type` as a member name in the structure
```
structure FailingStructureType {
  type: String,
}
```
5. Run `wash lint` which passes
6. Run `wash validate` which passes
7. Run `make` which fails
8. Change the type to use a non reserved word for the member name
```
structure WorkingStructureType {
  typeFoo: String,
}
```
9. Run `make` which succeeds

**Expected behavior**
Expectation is that `lint` or `validate` will fail and indicate that the use of reserved word is not permitted in this context. 

**Environment (please complete the following information) **
 - OS: Ubuntu 22.04.2 on 5.15.79.1-microsoft-standard-WSL2
 - Shell bash
 - wash Version 0.15.1

**Comment by brooksmtownsend** [comment]
Thanks for the report @cauldnz, perhaps there's a standard Rust library that we can take a look at for catching reserved keywords.

One thing to keep in mind is that these interfaces are language agnostic, so a type keyword (like `type`) may fail a Rust build but might succeed in a TinyGo interface. I think we should look into this as an extension to validate to warn and mention that specific keywords will fail in specific languages since that would help people name things in interfaces even if it's not in their primary development language.

**Comment by cauldnz** [comment]
OK... Good points on need to be language agnostic. I did a little digging... so hopefully this will get someone started (maybe even me) at some point.
Rust _reserved words_ are defined here: https://doc.rust-lang.org/reference/keywords.html
Rust _identifier_ specification is here: https://doc.rust-lang.org/reference/identifiers.html

Guidance is that these are not normative specification documents, rather merely indicative as to what's implemented in _rustc_ .

Sounds like there's really two things that we'd want to consider.
1. Implement checking within _wash validate_ against a list of reserved words. 
2. Emit a valid identifier into the generated Rust code by renaming the 

Current Wash implementation wraps the Atelier (https://github.com/johnstonskj/rust-atelier/tree/main/cargo-atelier) lint and validate implementations so may consider including the checks in the Lint module there. Some other keyword checking is already included: https://github.com/johnstonskj/rust-atelier/blob/main/atelier-core/src/action/lint/terms.rs

I've found one implementation that seeks to solve this problem when generating code by adding a Serde rename attribute. 
This helper app (https://github.com/ritz078/transform) correctly adds a rename attribute when it emits the Serde derive code. It also includes a list of the Rust keywords (for Rust 2018+) that may be useful.

So it emits something like this:
```
#[serde(rename = "type")]
pub type_field: String,
```

That helper app in turn relies on this set of tools (https://github.com/evestera/json_typegen) and the implementation in 
https://github.com/evestera/json_typegen/blob/master/json_typegen_shared/src/generation/rust.rs as below.

```
const RUST_KEYWORDS: &[&str] = &[
    "abstract", "alignof", "as", "become", "box", "break", "const", "continue", "crate", "do",
    "else", "enum", "extern", "false", "final", "fn", "for", "if", "impl", "in", "let", "loop",
    "macro", "match", "mod", "move", "mut", "offsetof", "override", "priv", "proc", "pub", "pure",
    "ref", "return", "Self", "self", "sizeof", "static", "struct", "super", "trait", "true",
    "type", "typeof", "unsafe", "unsized", "use", "virtual", "where", "while", "yield", "async",
    "await", "try",
];

fn type_or_field_name(
    name: &str,
    used_names: &HashSet<String>,
    default_name: &str,
    case_fn: fn(&str) -> String,
) -> Ident {
    let name = name.trim();
    let mut output_name = case_fn(name);
    if RUST_KEYWORDS.contains(&&*output_name) {
        output_name.push_str("_field");
    }
    if output_name.is_empty() {
        output_name.push_str(default_name);
    }
    if let Some(c) = output_name.chars().next() {
        if c.is_ascii_digit() {
            output_name = String::from("n") + &output_name;
        }
    }
    if !used_names.contains(&output_name) {
        return output_name;
    }
    for n in 2.. {
        let temp = format!("{}{}", output_name, n);
        if !used_names.contains(&temp) {
            return temp;
        }
    }
    unreachable!()
}
```

Another option may be to emit a _Raw Identifier_ https://rustwiki.org/en/rust-by-example/compatibility/raw_identifiers.html
