### ISSUE TITLE
[BUG] Error "Unable to start actor, Failed to find host " on trying to load hot reload actor from file

### ISSUE THREAD

**Issue by bcpeinhardt** [wasmCloud/wash-archive#440]
**Describe the bug**
When following the instructions at: https://wasmcloud.com/docs/app-dev/create-actor/update/
I get an error upon trying to create the hot reload actor: "Unable to start actor, Failed to find host "

**To Reproduce**
Follow the documentation at https://wasmcloud.com/docs/app-dev/create-actor/update/.

**Expected behavior**
To not get the error

**Screenshots**
![hot_reload_issue](https://user-images.githubusercontent.com/61021968/222506671-b597d0ec-8aab-4b01-b9fb-5c9f19b4749c.png)
![dashboard](https://user-images.githubusercontent.com/61021968/222506786-02737a1c-4bf0-4a75-9dbb-76b7af0a1257.png)

**Environment (please complete the following information) **
![system_information](https://user-images.githubusercontent.com/61021968/222506855-4ddab2f3-7b64-47e4-b5ba-76d3a4691d0d.png)

**Additional context**
It's incredibly likely I've simply done something wrong, and I really wish I knew what and didn't have to bother you xD

**Comment by connorsmith256** [comment]
Hi @bcpeinhardt, thank you for the bug report 🙏 You haven't done anything wrong! There is a bug in the latest release of the host. I've also confirmed that this bug has been fixed on main. The fix will be included in the next release of the host. Would you mind sharing which method you used to start your host?

**Comment by bcpeinhardt** [comment]
Hey @connorsmith256 !
I just did a `wash up` from my bash terminal, no docker or anything. I cargo installled wash if that helps.
For the time being I'll reinstall from the github source so I can keep exploring the awesomeness :)

**Comment by connorsmith256** [comment]
Thanks for the extra info. There is a workaround you could use if hot-loading is important to you, before we release the next version:

When starting a host with wash, you can specify the version to use, i.e.
```
WASMCLOUD_VERSION=v0.59.0 wash up
```

(v0.59.0 of the host doesn't have the bug that v0.60.0 of the host does)

A new version of the host with the fix should be released soon, but I hope this helps in the meantime!

**Comment by brooksmtownsend** [comment]
This was definitely an issue as of 0.59, but it was fixed by @vados-cosmonic in a future version
