### ISSUE TITLE
[BUG] wash does not report an error if `wash up -d` fails to start the host

### ISSUE THREAD

**Issue by connorsmith256** [wasmCloud/wash-archive#451]
**Describe the bug**
If for some reason wash fails to start the host -- say the user doesn't have libssl or another dependency -- wash isn't aware and doesn't report an error

**To Reproduce**
1. Modify `~/.wash/downloads/v0.60.0/bin/wasmcloud_host` so the `start` function execs an invalid command
1. Run `wash up -d`
1. Notice wash reports the host has started
2. Check `~/.wash/downloads/wasmcloud.log` and notice the host did not start/crashed

**Expected behavior**
If wash is responsible for starting the host, it should double-check that the host successfully started

**Comment by brooksmtownsend** [comment]
I think this is effectively a duplicate of #430, depending on if you think this is a bug or a feature request

**Comment by connorsmith256** [comment]
https://media3.giphy.com/media/3ohuAmeht2xOcCJCJa/giphy.gif
