### ISSUE TITLE
[FEATURE] Allow wash up to spin up multiple wasmCloud hosts in quick succession

### ISSUE THREAD

**Issue by vados-cosmonic** [wasmCloud/wash-archive#464]
**Is your feature request related to a problem? Please describe.**

Right now, when `wash up` runs, it uses the same ports and resources (ports for NATS for example) which means that starting more than one instance requires setting different ENV variables.

**Describe the solution you'd like**

Modfiy `wash` such that `wash up` can be run multiple times in quick succession to run multiple wasmCloud hosts.

**Describe alternatives you've considered**

Alternatively, we could update the documentation to more clearly call out how to use ENV variables properly to run multiple hosts.

**Additional context**

Connor worked on this in the past, so there is some support (ENV vars), may need to be reworked/expanded.

**Comment by thomastaylor312** [comment]
Yeah, this would be great to have! Moving this to TODO so anyone can claim if they want to work on it!

**Comment by brooksmtownsend** [comment]
Just a note for anyone trying to accomplish this before we take this task, you can do the following:
```
WASMCLOUD_DASHBOARD_PORT=4001 RELEASE_NAME=one wash up
WASMCLOUD_DASHBOARD_PORT=4002 RELEASE_NAME=two wash up --nats-connect-only
...
```

Just ensure that you launch hosts on ports other than `4000` and following the first one add the `--nats-connect-only` flag. The `RELEASE_NAME` variable is instructing the underlying erlang release to treat itself as a separate node, lower-level detail we'll handle when `wash up` handles this for you.
