### ISSUE TITLE
[BUG] Using --wasmcloud-start-only with wash up does not find locally installed versions

### ISSUE THREAD

**Issue by vados-cosmonic** [wasmCloud/wash-archive#492]
**Describe the bug**
When trying to test a local `wasmcloud-otp` version, `wash up --wasmcloud-version <local version>` does not find versions that have been installed to `~/.wash/downloads` when `--wasmcloud-start-only` is used.

The [related code](https://github.com/wasmCloud/wash/blob/462364d5d294b3527ebe022f942961a98a63784b/src/up/mod.rs#L289) seems to indicate that using the flag causes a failure to *always* occur.

**To Reproduce**
1. Build a custom version of `wasmcloud-otp` (i.e. run `make release` in `wasmcloud-otp/wasmcloud_host`
1. Install the custom version to `~/.wash/downloads` (ex. `~/.wash/downloads/v0.63.0`)
1. Attempt to run `wash up --wasmcloud-version <local version> --wasmcloud-start-only`

**Expected behavior**
`wash up` should recognize the custom version that has been added to `~/.wash/downloads`, with `--wasmcloud-start-only` specified.

**Screenshots**

N/A

**Environment (please complete the following information) **
 - OS: Linux
 - Shell: Bash
 - `wash` Version `v0.16.2`

**Additional context**

N/A

**Comment by connorsmith256** [comment]
Unmarked as stale. This one is still an issue 🙏
