### ISSUE TITLE
Docs: Add `wash build` docs to wasmcloud.dev

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/wash-archive#501]
Currently we have no documentation in this repo or on wasmcloud.dev for how `wash build` works and the various options for configuring it with `wasmcloud.toml`. I think our best option is to add documentation to wasmcloud.dev with different `wasmcloud.toml` examples and the recommendation that most people use `wash build`

**Comment by ghost** [comment]
Closing in favor of https://github.com/wasmCloud/wasmcloud.com-dev/issues/168 over on the wasmcloud.com repo.
