### ISSUE TITLE
Make Tinygo Target Configurable

### ISSUE THREAD

**Issue by jordan-rash** [wasmCloud/wash-archive#512]
Would like to make the below line configurable.  tinygo will take either a `wasm` or `wasi` target.  The `wasm` target is what we have always used, but it does pull in all the JS stuff.  I am just starting the test the `wasi` target, so I don't know what we want to make the default at this point.  Probably `wasm` to reduce confusion? 🤷🏼 

https://github.com/wasmCloud/wash/blob/f7b34341e177ce72a3a50366e476b752a9e9d54d/crates/wash-lib/src/build.rs#L198

**Comment by jordan-rash** [comment]
cc: @brooksmtownsend && @mattwilkinsonn 

I assume this is a "Good First Issue", but I'm not sure if what discussions need to be had on defaults

**Comment by brooksmtownsend** [comment]
Yeah @jordan-rash I think we want to make use of https://github.com/wasmCloud/wash/blob/f7b34341e177ce72a3a50366e476b752a9e9d54d/crates/wash-lib/src/parser/mod.rs#L50 instead of hardcoded `wasm` there!

edit: this will just go in the wasmcloud.toml
```toml
[actor]
wasm_target = "wasm|wasi"
```

**Comment by jordan-rash** [comment]
I noticed that the tinygo build function only takes in the common_config and the tinygo_config, while the rust build function takes in the actor_config (where that setting lives) as a third parameter.  Is there a reason that the actor_config was left out?  

Also, it looks like that setting defaults to wasm32_unknown_unknown.  If we were to use it, we would have to make the default conditional on the language.  I wonder if it would be easier to move the target setting to the rust_config / tinygo_config sections??

(Sorry for the lack of formatting, I'm on my phone)

**Comment by brooksmtownsend** [comment]
Looks like you're probably right in both cases, we should also put in actor config and let the default be dictated by the language or overrided

**Comment by jordan-rash** [comment]
Also need to address the scheduler flag

Right now, most the automation I use compiles like so 
`tinygo build -target=wasi -scheduler=none -o output_path .`
