### ISSUE TITLE
[FEATURE] start provider from file

### ISSUE THREAD

**Issue by ricochet** [wasmCloud/wash-archive#540]
**Is your feature request related to a problem? Please describe.**
A `file:///` reference works for `wash ctl start actor` but not `wash ctl start provider`. 

**Describe the solution you'd like**
Add start from file for providers to aid in faster dev iteration.

**Describe alternatives you've considered**
N/A

**Additional context**
Related: https://github.com/wasmCloud/wash/issues/509 https://github.com/wasmCloud/wash/issues/372
Discussion: https://wasmcloud.slack.com/archives/CS38R7N9Y/p1683002116592459

**Comment by connorsmith256** [comment]
@ricochet I think wash is doing the right thing as-is and the fix needs to be in the OTP host. We filed an issue here: https://github.com/wasmCloud/wasmcloud-otp/issues/639

**Comment by connorsmith256** [comment]
Fixed by https://github.com/wasmCloud/wasmcloud-otp/pull/641
