### ISSUE TITLE
[BUG] fedora 38 (rpm): repo doesn't contain wash

### ISSUE THREAD

**Issue by LennyPenny** [wasmCloud/wash-archive#581]
**Describe the bug**
When using the rpm repo as explained in the readme, wash is not available in the repos for installation

**To Reproduce**
1. Boot fedora 38
2. Setup the rpm repo
3. `curl -s https://packagecloud.io/install/repositories/wasmcloud/core/script.rpm.sh | sudo bash`
4. try to install wash while updating the repos: `sudo dnf install wash --refresh`
5. error: `Error: Unable to find a match: wash`

I also tried wash-cli. Nothing containing wash is in the repos. 

**Expected behavior**
Wash should be installed

**Environment (please complete the following information) **
 - OS: Fedora 38
 - Shell bash

**Comment by connorsmith256** [comment]
Thank you again @LennyPenny ! It turns out we didn't have Fedora 38 in our list of distros where we publish wash. I released wash v0.17.5 to Fedora 38 today, so the above commands should now work :)
