### ISSUE TITLE
[BUG] Cargo install of v0.17.3 fails

### ISSUE THREAD

**Issue by LennyPenny** [wasmCloud/wash-archive#582]
**Describe the bug**
Due to #581 I tried the other install method mentioned in the readme, namely to install using cargo install method. However its failing due to missing type annotations. 

**To Reproduce**
1. use rustup to install a stable toolchain
2. `cargo install wash-cli`
3. See error:
> Compiling clap_complete v4.3.0
error[E0283]: type annotations needed
   --> /home/lenny/.cargo/registry/src/github.com-1ecc6299db9ec823/wash-lib-0.8.1/src/generate/mod.rs:319:39
    |
319 |         let file_path = search_folder.join(name.borrow());
    |                                       ^^^^      ------ type must be known at this point
    |                                       |
    |                                       cannot infer type of the type parameter `P` declared on the method `join`
    |
    = note: multiple `impl`s satisfying `str: Borrow<_>` found in the following crates: `bstr`, `core`:
            - impl Borrow<bstr::bstr::BStr> for str;
            - impl<T> Borrow<T> for T
              where T: ?Sized;
help: consider specifying the generic argument
    |
319 |         let file_path = search_folder.join::<&Borrowed>(name.borrow());
    |                                           +++++++++++++
For more information about this error, try `rustc --explain E0283`.
error: could not compile `wash-lib` due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `wash-cli v0.17.2`, intermediate artifacts can be found at `/tmp/cargo-installm4q12v`

**Expected behavior**
It should compile and install successfully. 

**Environment (please complete the following information) **
 - OS: fedora 38
 - Shell bash
 - wash Version v0.17.3
 - rust: 
![image](https://github.com/wasmCloud/wash/assets/4027243/7836240b-7f9f-4dd3-a6ae-3b2bfef65116)

**Comment by connorsmith256** [comment]
Thank you for the report @LennyPenny ! This error was fixed in main [a couple weeks ago](https://github.com/wasmCloud/wash/commit/ec4e20ba0b69636c62fe0d646ea79b5d1314235f)

We should have a new release soon. In the meantime, the `0.18.0-alpha.2` version is available, if you're comfortable running off this alpha release for a little bit

**Comment by connorsmith256** [comment]
Quick followup: v0.17.4 is a patch release that contains this fix and is [currently building](https://github.com/wasmCloud/wash/actions/runs/5135203042) 🚀 

EDIT: done! The latest wash-cli should be installable with cargo
