### ISSUE TITLE
[FEATURE] Support capability provider JSON schemas

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wash-archive#590]
**Describe the solution you'd like**
The newest versions of `wascap` and `provider-archive` allow for capability provider claims to include a JSON payload for a configuration schema. I would like to be able to view/extract the schema via the `inspect` sub-command on PARs, and I would also like to be able to supply the path to a JSON file containing the schema for when generating a `par` file.

**Comment by connorsmith256** [comment]
@autodidaddict this is done now, right?

**Comment by brooksmtownsend** [comment]
Should be closed with #677
