### ISSUE TITLE
[FEATURE] `wash dev`

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/wash-archive#600]
To help tighten the inner dev loop, we should add a command to wash (we've been also discussing a new experiments subcommand to put these under e.g. `wash experiments dev` ) that watches for changes, runs `wash build` and then `wash deploy` . This could even leverage something like `wash spy` (see #599).

Basic psuedocode

*   on `wash dev`
    *   `wash up` if not up yet (make sure to enable FS upload)
    *   run `wash build`
    *   if actor is already running
        *   `wash ctl stop <actor>`
    *   `wash ctl start <file>`
    *   watch fs for changes
    *   on change run `wash build`

So an example flow would look like this:

```bash
$ wash dev
Building `echo`
Pushing `echo`
Deployed `echo`
Watching for changes...

Received invocation # wash spy part
{ "method": "GET", ...}

src/lib.rs changed, rebuilding
Building `echo`
Pushing `echo`
Deployed `echo`
```

**Comment by thomastaylor312** [comment]
@vados-cosmonic said he was going to work on this

**Comment by vados-cosmonic** [comment]
Yep, thanks @thomastaylor312  -- open to input as well on ergonomics, so please feel free to comment in this issue if you have any feedback/wants!

**Comment by brooksmtownsend** [comment]
implemented in https://github.com/wasmCloud/wash/pull/610
