### ISSUE TITLE
[BUG] wash build with a TinyGo actor fails with No such file or directory

### ISSUE THREAD

**Issue by protochron** [wasmCloud/wash-archive#611]
**Describe the bug**
If you do not have tinygo installed and are trying to build a tinygo actor, you get a cryptic error message (`No such file or directory (os error 2)` ) instead of a descriptive error message.

**To Reproduce**
1. Uninstall tinygo
2. `wash new` -- create a tinygo template
3. `wash build` and watch it fail

**Expected behavior**
I would expect an error message telling me that tinygo is missing and to go install it.

**Screenshots**

**Environment (please complete the following information) **
 - OS: MacOS
 - Shell zsh, powershell
 - wash 0.17

**Additional context**

**Comment by ghost** [comment]
Was fixed in #636!
