### ISSUE TITLE
[FEATURE] Add a `--deploy` flag to `wash app put`

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/wash-archive#623]
**Is your feature request related to a problem? Please describe.**

Often times you just want to put and deploy a manifest all at the same time, particularly when testing or kicking the tires with wasm cloud. 

**Describe the solution you'd like**

We should add a `--deploy` flag to the `wash app put` command so we can deploy. The behavior would look something like this:

```shell
$ wash app put --deploy manifest.yaml
Manifest published!
Manifest deployed!
```

**Comment by connorsmith256** [comment]
I like this. What do you think about `wash app put --deploy manifest.yaml` vs `wash app deploy --manifest manifest.yaml`?

I.e. 1) is deploy while putting, whereas 2) is deploy from a manifest (implicitly `put`)

**Comment by brooksmtownsend** [comment]
Right now you can do `wash app deploy ./manifest.yaml` 🤔

**Comment by thomastaylor312** [comment]
That was definitely unclear from the help text:

```
wash app deploy -h
Deploy an app (start a deployment monitor)

Usage: wash app deploy [OPTIONS] <name> [version]

Arguments:
  <name>     Name of the app specification to deploy
  [version]  Version of the app specification to deploy, defaults to the latest created version
```

I'll close this and open a new issue to fix that

**Comment by thomastaylor312** [comment]
Open #626 to handle it
