### ISSUE TITLE
[FEATURE] `wash app put` should support other forms of manifest input

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/wash-archive#624]
**Is your feature request related to a problem? Please describe.**

Right now, you can only use `wash app put` with a local file. Anyone coming from tools like `nomad` or `kubectl` is used to having a way to read a manifest from STDIN or from a URL

**Describe the solution you'd like**

I would like `wash app put` to support fetching a manifest from a URL or reading from stdin:

```shell
# read from stdin
$ wash app put -
# read from URL
$ wash app put https://raw.githubusercontent.com/wasmCloud/examples/main/actor/kvcounter/wadm.yaml
```

**Comment by brooksmtownsend** [comment]
Additionally, since `wash app deploy` can nicely wrap a `put` and then `deploy`, it should work for that as well

**Comment by ahmedtadde** [comment]
I did some work on this and put out a [draft PR](https://github.com/wasmCloud/wash/pull/851). I haven't done testing yet but will do so. I just wanted to put a draft out to get some feedback on whether the proposed changes are acceptable/viable from your p.o.v.

**Comment by connorsmith256** [comment]
Closed by https://github.com/wasmCloud/wash/pull/875
