### ISSUE TITLE
Add ability to "skip" words in REPL.

### ISSUE THREAD

**Issue by tiptop96** [wasmCloud/wash-archive#67]
In a terminal you can use option/alt + left/right arrow to move the cursor across a word. We should support this in the REPL as well.

To do this we need to define what constitutes a word/whitespace. E.g. in some terminals (I think most) this operation would skip to the next dash but would pass trough an underscore. I suggest we aim for something along those lines, meaning we atleast recognizing dashes and spaces as "whitespace". Any suggestions are more than welcome here!

Also we noticed that there is no out of the box support for detecting a mac keyboards option key as a [`KeyModifier`](https://docs.rs/crossterm/0.18.2/crossterm/event/struct.KeyModifiers.html) in `crossterm` so we need to figure out how to do that.

**Comment by brooksmtownsend** [comment]
From #95 , I've added in a few
```
//TODO(issue #67):
```
snippets in the code, refer to these if looking to tackle this issue

**Comment by autodidaddict** [comment]
wash REPL is being deprecated, as such closing this issue.
