### ISSUE TITLE
wasmCloud Rust host is launched with wash up

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wash-archive#693]
Launching the Rust host with `wash up` effectively completes our roadmap goal of a feature complete Rust host. This depends on a few other issues so this isn't ready for work yet.

**Comment by ricochet** [comment]
Started on this: https://github.com/wasmCloud/wash/compare/main...rust-host-default

**Comment by brooksmtownsend** [comment]
Fixed in #759
