### ISSUE TITLE
[BUG] Unable to redeploy the same application after deletion

### ISSUE THREAD

**Issue by xpepermint** [wasmCloud/wash-archive#695]
**Describe the bug**
I've encountered a fairly frustrating issue with the wash CLI. Once an application is deleted, it appears that the same application cannot be redeployed.

**To Reproduce**
1. Begin with a fresh wasmCloud installation as outlined in the documentation.
2. Execute `wash up` in one terminal.
3. Create a new actor with `wash new actor hello`.
4. Deploy the app using `wash app deploy wadm.yaml`.
5. Delete the app with `wash app del hello v0.0.1`.
6. Attempt to redeploy the same app using `wash app deploy wadm.yaml`.

Following these steps results in an error: `Could not put manifest to deploy. Internal storage error.`

In addition, I noticed a warning message: `[warning] Failed to look up link definition with ID EE5DDC....` It also appears that link definitions are not being automatically removed upon app deletion.

Interestingly, I found that after rebooting the machine, the same app could be redeployed. I checked the `/tmp` directory but found no relevant files or data. This suggests that the loaded configuration might only be appending to memory and is not being refreshed properly.

**Environment**
 - OS: Ubuntu, MacOS
 - Shell: zsh
 - wash Version 0.19.1

**Comment by thomastaylor312** [comment]
Sorry for the frustration @xpepermint. So this was a bug in wadm (https://github.com/wasmCloud/wadm/issues/129) and is fixed, but the latest version of wadm will fix this. The default in wash is 0.4 and that is the one that has the bug 

In the meantime, you can use `--wadm-version` flag to use the latest alpha version: https://github.com/wasmCloud/wadm/releases/tag/v0.5.0-alpha.2
