### ISSUE TITLE
[BUG] wash app doesn't distinguish between deployed and latest versions

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wash-archive#699]
**Describe the bug**
When I do `wash app list`, the output displays the latest version of the model, _not_ the currently deployed version. This means that in all cases where the latest version isn't the deployed version, wash displays misleading or incorrect information.

**To Reproduce**
* Start with a deployed app, then `wash app deploy` an _older_ version. Note the output of `wash app list` shows an undeployed version
* Start with a deployed app, then `wash app put` a _newer_ version that _isn't deployed_. Note the output of `wash app list` shows an undeployed version

**Expected behavior**
I should be able to see _both_ the latest version _and_ the currently deployed version

**Comment by brooksmtownsend** [comment]
Woah, looks like the JSON output already includes this!
```
~/github.com/wasmcloud/examples/petclinic ➜ wash app list -o json

{
  "success": true,
  "apps": [
    {
      "deployed_version": "v0.0.1",
      "description": "wasmCloud Pet Clinic Sample",
      "name": "petclinic",
      "status": "compensating",
      "version": "v0.0.5"
    }
  ]
}
```

I'm upgrading this to a good-first-issue because that information is available 😄
