### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by yordis** [wasmCloud/wash-archive#733]
Hey folks, I wonder if adding at least the minimal setup to contribute to the Front End app is possible.

The app is up and running with `npm install` and `npm run dev,` but I am unsure how to set up the Lattice. I have the Elixir-based runtime, so I wonder if this is only for the Rust one or how I should run the runtime so I can focus on the UI.

Ideally, `docker compose up -d` and I get to focus on the frontend.

**Comment by connorsmith256** [comment]
Hi @yordis, which of these are you looking for?
1) guidelines on how the wasmCloud org handles contributions
2) setup instructions for how to run a wasmCloud host
3) instructions for how to iterate on the new dashboard UI locally
4) something else? 🙂 

For 1), you can check out the [top-level contributing guide](https://github.com/wasmCloud/wasmCloud/blob/main/CONTRIBUTING.md)
For 2), you'll want to [install wash](https://wasmcloud.com/docs/installation) and then run `wash up`
For 3), I believe you can run `npm i && npm run dev` from the `wash/packages/washboard` directory

**Comment by yordis** [comment]
> instructions for how to iterate on the new dashboard UI locally

That ^

---

Probably a good idea if I remove [my `docker, compose` setup](https://github.com/yordis/.dotfiles/blob/9be6b90b4f5f9b6c88573d0e8f910def0fff377e/roles/docker/src/docker-compose.yml#L402-L420). Document for the usage `wash up` vs. docker-compose setups, vs. local build

> For 3), I believe you can run npm i && npm run dev from the wash/packages/washboard directory

What would help here is to document the ports somewhere. Maybe they already exist (sorry if I missed them), or at the very least, in the frontend README.md, whatever port I should put to connect to the `nats.ws` web socket.

Is that Front End Nats web socket a connection directly to Nats?

**Comment by connorsmith256** [comment]
Understood, and thanks for the feedback 🙌 I like the idea of adding a README/DEVELOPMENT for the washboard directory, and/or calling this out from wash's README/DEVELOPMENT page(s). @lachieh what do you think?

For your immediate questions:
- the washboard development lifecycle is handled by [vite](https://vitejs.dev/), where the [default port is 5173](https://vitejs.dev/config/server-options.html#server-port)
- the washboard connects to a NATS server at [`ws://localhost:4001` by default](https://github.com/wasmCloud/wash/blob/a74b50297496578e5e6c0ee806304a3ff05cd073/packages/washboard/src/lattice/lattice-service.ts#L70), although this can be overridden via the UI
- to specify a websocket port when starting wasmCloud via wash, you'll want to include the [`--nats-websocket-port`](https://github.com/wasmCloud/wash/blob/b0e746be713d070b4400294ec401b87444bd5741/src/up/mod.rs#L102) option

All this information should definitely be documented 😅

**Comment by lachieh** [comment]
A README and a DEVELOPMENT guide inside the washboard folder and a section in the root README regarding the UI would be beneficial, yeah.

@yordis if you want to update your setup, the `NATS_WEBSOCKET_PORT` env variable will determine if the nats websocket is started and on which port it attaches. There isn't a container for the UI, but you could probably serve up the static files with nginx.

As @connorsmith256 mentioned, the build is handled by vite, which you can start in dev mode (hotreloading, etc) with `npm run dev`.

**Comment by brooksmtownsend** [comment]
Closed by #735
