### ISSUE TITLE
Tab completion for REPL

### ISSUE THREAD

**Issue by ChrisRx** [wasmCloud/wash-archive#74]
As a user it would be nice to have tab completion for the REPL, especially for things like actor/provider IDs.  I think a good initial implementation would be upon pressing tab:

* Complete any verbs/commands (e.g. `link`, `start actor`, `get host`)
* If following a command that expects an argument, refresh a list of actors/providers/etc from the host (depending upon context) and allow completion from the generated list.

**Comment by VestigeJ** [comment]
Another thought could be to do what Docker does with container IDs where the first 'n' distinct characters work to grab the IDs.

**Comment by autodidaddict** [comment]
REPL is deprecated, closing this issue
