### ISSUE TITLE
[BUG] Spurious error when trying to `wash app deploy`

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/wash-archive#748]
**Describe the bug**

If you have started a host with `wash up` and then run `wash app deploy nonexistentfile.yaml` it gives a very non-helpful error

```
wash app deploy wadm.yaml

Invalid subject: Found extra components of subject
```

**To Reproduce**
1. Run `wash up`
1. In another terminal, run `wash app deploy foo.yaml`
1. See error

**Expected behavior**

I would expect an error that says the file wasn't found

**Screenshots**

**Environment (please complete the following information) **
 - OS: MacOS
 - wash Version 0.19.1

**Comment by brooksmtownsend** [comment]
OH this is because we're assuming the app name is `foo.yaml` so the subject ends up including the `.`, adding an extra component. Without the extension you get a normal error

```
~/github.com/wasmcloud/wash ➜ cargo run -- app deploy foo     
    Finished dev [unoptimized + debuginfo] target(s) in 0.43s
     Running `target/debug/wash app deploy ree`

Model with the name foo not found
```
