### ISSUE TITLE
[BUG] Better log signal for host started

### ISSUE THREAD

**Issue by ricochet** [wasmCloud/wash-archive#761]
**Describe the bug**
We're working towards releasing the rust host as default but ran into an issue where we don't have a clear log message like with the OTP host to validate whether or not the host started successfully (from logs alone).

**Expected behavior**
Two parter here. Update the host to give a log we can key off of then update the test then fix this line:
https://github.com/wasmCloud/wash/blob/f9279294ea7602ad6bbc55a5f3dc8940f2d46d71/crates/wash-lib/src/start/wasmcloud.rs#L491

**Environment (please complete the following information) **
 - OS: macos
 - Shell zsh
 - wash Version [e.g. 0.2.0]

**Additional context**

**Comment by brooksmtownsend** [comment]
Think this was fixed by wasmcloud/wasmcloud#619

**Comment by connorsmith256** [comment]
@brooksmtownsend The host emits a better start message now, but the wash tests need to be updated to check for the updated message :)
