### ISSUE TITLE
[BUG] docs.rs documentation broken

### ISSUE THREAD

**Issue by rvolosatovs** [wasmCloud/wash-archive#831]
**Describe the bug**
docs.rs is unable to build the documentation of `wash-lib`

**To Reproduce**
1. Go to https://docs.rs/crate/wash-lib/latest

**Expected behavior**
Docs available on docs.rs

**Screenshots**
![2023-09-26-22:15:05-screenshot](https://github.com/wasmCloud/wash/assets/12877905/36923435-0f2a-4c2e-8d3f-55cf75068534)

**Environment (please complete the following information)**
 - wash Version 0.10.1

**Additional context**
0.9.1 was the last successful build

**Comment by connorsmith256** [comment]
Here's the error from docs.rs:

```
[INFO] [stderr]   Error: `https://github.com/bytecodealliance/wasmtime/releases/download/v12.0.1/wasi_snapshot_preview1.command.wasm` is not a valid URL
[INFO] [stderr] 
[INFO] [stderr]   Caused by:
[INFO] [stderr]       0: error sending request for url (https://github.com/bytecodealliance/wasmtime/releases/download/v12.0.1/wasi_snapshot_preview1.command.wasm): error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution
[INFO] [stderr]       1: error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution
[INFO] [stderr]       2: dns error: failed to lookup address information: Temporary failure in name resolution
[INFO] [stderr]       3: failed to lookup address information: Temporary failure in name resolution
```

I just released v0.11 of wash-lib, so hopefully this doesn't happen again 🤞

**Comment by connorsmith256** [comment]
Unfortunately it happened again. I'm not sure, but I suspect it's because `build.rs` is trying to download the adapter, and the container that docs.rs uses doesn't support network access?

**Comment by brooksmtownsend** [comment]
I assume that means that we will have to bundle the adapter in with our repo?

**Comment by rvolosatovs** [comment]
> I assume that means that we will have to bundle the adapter in with our repo?

Kind of, what we could do is introduce a feature flag and enable it for docs.rs. I've seen other projects do that.

**Comment by connorsmith256** [comment]
Yeah I think a docs FF is the quickest solution

**Comment by connorsmith256** [comment]
We should be able to use [custom metadata for docs.rs](https://docs.rs/about/metadata) to enable the feature flag. Note the fix will be to https://github.com/wasmCloud/wasmcloud-component-adapters, since that's where the `build.rs` is

I started filing a good first issue but since that repo isn't well-known, I think a maintainer will have to take this one on

**Comment by connorsmith256** [comment]
Fixed :) https://docs.rs/wash-lib/latest/wash_lib/
