### ISSUE TITLE
[FEATURE] Add comands for actor claim management (add/list/remove)

### ISSUE THREAD

**Issue by vados-cosmonic** [wasmCloud/wash-archive#856]
**Is your feature request related to a problem? Please describe.**

Currently, managing [claims](https://wasmcloud.com/docs/hosts/security#claims) (listing, adding, and removing them) on built actors requires writing Rust code (usually by utilizing [`wascap`](https://crates.io/crates/wascap)) -- building this functionality into `wash` would make it far more accessible to people building actors with `wash`.

**Describe the solution you'd like**

Add commands for managing claims on built actors to wash, in particular, users should be able to:

- List existing claims on a built & signed wasm module
- Add a claim to an existing built & signed module
- Remove a claim from a built & signed module

**Describe alternatives you've considered**

N/A

**Additional context**

The [code for `wash inspect` is a great place to reference](https://github.com/wasmCloud/wash/blob/9c01456439424ce5dfd919d6c2cb4e68fc05cb5b/crates/wash-lib/src/cli/inspect.rs)

Consider using an example like [`echo-wasi-preview2`](https://github.com/wasmCloud/examples/tree/main/actor/echo-wasi-preview2) for testing the build process. Note that it has [one claim which is for the httpserver contract](https://github.com/wasmCloud/examples/blob/main/actor/echo-wasi-preview2/wasmcloud.toml#L14)

**Comment by connorsmith256** [comment]
I think we should merge this with https://github.com/wasmCloud/wasmCloud/issues/842

**Comment by vados-cosmonic** [comment]
That's a great idea -- I'll close this one for now and make a comment in wasmCloud/wasmCloud#842
