### ISSUE TITLE
Move this crate under the wasmCloud repository

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wash-archive#86]
`wash` is a command line tool directly related and used for [wasmCloud](https://github.com/wasmCloud/wasmcloud), and in order to consolidate some of our repositories we should move wash under the `crates/` directory there. Github actions will need to be modified, as well as README and Cargo.toml metadata elements that involve a repository location to ensure it is still locatable from the crate. We will also need to change the github actions located in this repository so they still are usable in the main wasmcloud repository.

Last but not least, we should move all issues over, and merge the two git histories in order to preserve contributors and a consistent history.

**Comment by stevelr** [comment]
I vote close this and not merge
