### ISSUE TITLE
[BUG] Unneeded output when creating keys

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/wash-archive#860]
**Describe the bug**

When running `wash build` (or any step that generates a key for you), this output is written to the terminal:

```
{"keygen":"true","path":"/Users/taylor/.wash/keys/blahblahblah_module.nk","status":"No keypair found"}
```

That message shouldn't be written by default (probably should just be logged)

**To Reproduce**

- Create an actor with a name you haven't used before: `wash new actor -t hello blahblahblah && cd blahblahblah`
- `wash build`
- See output

**Expected behavior**

The "no keypair found" should not be echoed to the terminal

**Comment by connorsmith256** [comment]
Fixed by https://github.com/wasmCloud/wash/pull/799 !
