### ISSUE TITLE
[FEATURE] Add alias delete to del command for `wash app`

### ISSUE THREAD

**Issue by ricochet** [wasmCloud/wash-archive#866]
**Is your feature request related to a problem? Please describe.**
Enhancement

**Describe the solution you'd like**
Change `del` to alias and `delete` as the main command.

**Describe alternatives you've considered**
 I was surprised that all of the other commands are long and delete is the only shortened one.

Alternatively, add an alias for `wash app delete` to `wash app del`.

The main reason why I'd prefer to see `delete` in the help info as it's easier to read.

```bash
wash app --help
Manage declarative applications and deployments (wadm) (experimental)

Usage: wash app [OPTIONS] <COMMAND>

Commands:
  list      List application specifications available within the lattice
  get       Retrieve the details for a specific version of an app specification
  history   Retrieve the version history of a given model within the lattice
  del       Delete a model version
  put       Puts a model version into the store
  deploy    Deploy an application to the lattice
  undeploy  Undeploy an application, removing it from the lattice
  help      Print this message or the help of the given subcommand(s)

Options:
  -o, --output <OUTPUT>  Specify output format (text or json) [default: text]
      --experimental     Whether or not to enable experimental features [env: WASH_EXPERIMENTAL=]
  -h, --help             Print help
```

**Comment by WallysFerreira** [comment]
Hey I'd like to work on this

**Comment by connorsmith256** [comment]
Sounds great @WallysFerreira!

**Comment by WallysFerreira** [comment]
Just to make sure I'm getting it right. In the AppCliCommand I need to change the clap name from "del" to "delete", then add "del" as an alias with clap alias?

**Comment by LiamRandall** [comment]
Sounds right to me!

**Comment by connorsmith256** [comment]
Resolved by https://github.com/wasmCloud/wash/pull/876
