### ISSUE TITLE
can't scroll Tui Log pane

### ISSUE THREAD

**Issue by stevelr** [wasmCloud/wash-archive#89]
As a wash user, I want to be able to read the logs, but sometimes they scroll out of view and there isn't a way to read them. Could a keycode be added to enable scrolling?

**Comment by brooksmtownsend** [comment]
I'll take a look into this, we have manual control over the output window (as you can see you can scroll with SHIFT+UP/DOWN there) but the `tui_logger` widget has proven to be a bit closed off. We recently updated a few versions so there might be an option now

**Comment by brooksmtownsend** [comment]
It appears that the ability to scroll is something that's internal to the tui logger crate. I think this would be a great feature to have, so I've opened up https://github.com/gin66/tui-logger/issues/12 to see if we can get something implemented in the crate itself, or just in case I'm missing a way to do this in the first place. Thanks @stevelr for the issue 🥇

**Comment by brooksmtownsend** [comment]
After further investigation, it appears that `tui_logger` `v0.6.0` implements scrolling with PAGEUP / PAGEDOWN keybindings. The upgrade to `tui_logger` `v0.6.0` will be breaking, so it will have to be done with care, but it should not change our API when we do it.

**Comment by brooksmtownsend** [comment]
@stevelr #95 has been opened to tackle this issue, would love your feedback (if you're building from source, would also love your feedback on how it works for you)

**Comment by tobiww** [comment]
> @stevelr #95 has been opened to tackle this issue, would love your feedback (if you're building from source, would also love your feedback on how it works for you)

 
I will try it out, but won't be able to until this weekend.

**Comment by stevelr** [comment]
> @stevelr #95 has been opened to tackle this issue, would love your feedback (if you're building from source, would also love your feedback on how it works for you)

I will try it out, but won't be able to until this weekend.

**Comment by brooksmtownsend** [comment]
Closed by #95
