### ISSUE TITLE
Support generating wasmcloud projects with wash

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wash-archive#93]
CC @pkedy 

Currently, the waPC CLI ([repo here](https://github.com/wapc/cli)) allows you to generate waPC projects (and therefore wasmcloud projects) for our three main supported languages (Rust, AssemblyScript, and TinyGo). After the project is generated, a `widl` file can be dropped into the project structure and used directly to generate  This is incredibly useful for generating scaffold code for wasmcloud actor interfaces, actors, and providers.

As it stands today, the preferred method to generate an actor for wasmcloud development is to run the following:
```shell
cargo generate --git https://github.com/wasmCloud/new-actor-template
```

As you can see, this is a Rust specific implementation. Currently, the best way to suggest writing AssemblyScript or TinyGo actors is to point developers to our actor interfaces which provide sample actor code in their README's or documentation.

An ideal solution to this problem would be to utilize the code generation functionality of the waPC CLI, or otherwise an actor scaffold template, encapsulated into a `wash` command. The CLI API could look like:
```shell
wash generate rust myactor
wash generate assemblyscript myactor-as
wash generate tinygo myactor-go
```
Generating an actor in this way should provide similar functionality to the above `cargo generate`, but for all of the languages that we support. This would allow developers new to `wasmcloud` to directly generate their project in their language of choice using `wash`.

**Comment by autodidaddict** [comment]
@stevelr does this issue still apply given the new world where `weld` and `smithy` exist?

**Comment by stevelr** [comment]
No longer relevant
