### ISSUE TITLE
Correct capitalization of wasmCloud to wasmcloud

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wash-archive#97]
This should just be a project-wide replace of `wasmCloud` with `wasmcloud` to match our branding.

**Comment by javiercaamano** [comment]
Hi, nedd help? can u tell how can I help you?
I'm practicing in issues and PR's on GitHub and I'm lookig for easy task to do. I'm beginner.

**Comment by brooksmtownsend** [comment]
Hi @javiercaamano, happy to take the help! See the original comment, the issue should be fairly straightforward. Feel free to submit a PR from your personal fork if you decide to take this on

**Comment by brooksmtownsend** [comment]
Closed by #100
